; generated by hcbcomp-8080
; source: gets.b


section text
extern getchar
global gets

section text
	; function gets prologue
gets:
	lxi h, 65532
	dad sp
	sphl
	lxi h, 0
	dad sp
	push h
	lxi h, 0
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
.L0:
	lxi h, 0
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 254
	pop d
	xchg
	mov a, l
	sub e
	mov l, a
	mov a, h
	sbb d
	mov h, a
	jc .L3
	lxi h, 0
	jmp .L4
.L3:
	lxi h, 1
.L4:
	; while
	mov a, h
	ora l
	jz .L2
	lxi h, 2
	dad sp
	push h
	lxi h, getchar
	; call getchar
	; call getchar(0 args)
	call getchar
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	lxi h, 2
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 10
	pop d
	mov a, l
	sub e
	jnz .L5
	mov a, h
	sbb d
	jnz .L5
	lxi h, 1
	jmp .L6
.L5:
	lxi h, 0
.L6:
	; if
	mov a, h
	ora l
	jz .L7
	jmp .L2
.L7:
	lxi h, 2
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 13
	pop d
	mov a, l
	sub e
	jnz .L9
	mov a, h
	sbb d
	jnz .L9
	lxi h, 1
	jmp .L10
.L9:
	lxi h, 0
.L10:
	; if
	mov a, h
	ora l
	jz .L11
	jmp .L2
.L11:
	lxi h, 2
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 1
	xchg
	lxi h, 0
	mov a, l
	sub e
	mov l, a
	mov a, h
	sbb d
	mov h, a
	pop d
	mov a, l
	sub e
	jnz .L13
	mov a, h
	sbb d
	jnz .L13
	lxi h, 1
	jmp .L14
.L13:
	lxi h, 0
.L14:
	; if
	mov a, h
	ora l
	jz .L15
	jmp .L2
.L15:
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 0
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	pop d
	dad h
	dad d
	push h
	lxi h, 2
	dad sp
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	lxi h, 0
	dad sp
	push h
	lxi h, 0
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 1
	pop d
	dad d
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	jmp .L0
.L2:
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 0
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	pop d
	dad h
	dad d
	push h
	lxi h, 0
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	lxi h, 0
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	; return
	ret
	; function gets epilogue
	ret
