; generated by hcbcomp-8080
; source: strcmp.b


section text
global strcmp

section text
	; function strcmp prologue
strcmp:
	lxi h, 65534
	dad sp
	sphl
	lxi h, 0
	dad sp
	push h
	lxi h, 0
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
.L0:
	lxi h, 1
	; while
	mov a, h
	ora l
	jz .L2
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 0
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	pop d
	dad h
	dad d
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 0
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	pop d
	dad h
	dad d
	mov a, m
	inx h
	mov h, m
	mov l, a
	pop d
	mov a, l
	sub e
	jnz .L3
	mov a, h
	sbb d
	jz .L4
.L3:
	lxi h, 1
	jmp .L4
.L4:
	lxi h, 0
	; if
	mov a, h
	ora l
	jz .L5
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 0
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	pop d
	dad h
	dad d
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 0
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	pop d
	dad h
	dad d
	mov a, m
	inx h
	mov h, m
	mov l, a
	pop d
	xchg
	mov a, l
	sub e
	mov l, a
	mov a, h
	sbb d
	mov h, a
	jc .L7
	lxi h, 0
	jmp .L8
.L7:
	lxi h, 1
.L8:
	; if
	mov a, h
	ora l
	jz .L9
	lxi h, 1
	xchg
	lxi h, 0
	mov a, l
	sub e
	mov l, a
	mov a, h
	sbb d
	mov h, a
	; return
	ret
.L9:
	lxi h, 1
	; return
	ret
.L5:
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 0
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	pop d
	dad h
	dad d
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 0
	pop d
	mov a, l
	sub e
	jnz .L11
	mov a, h
	sbb d
	jnz .L11
	lxi h, 1
	jmp .L12
.L11:
	lxi h, 0
.L12:
	; if
	mov a, h
	ora l
	jz .L13
	lxi h, 0
	; return
	ret
.L13:
	lxi h, 0
	dad sp
	push h
	lxi h, 0
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 1
	pop d
	dad d
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	jmp .L0
.L2:
	; function strcmp epilogue
	ret
