M = @make --no-print-directory --silent $@ -C
INSTDIR = /usr/local/bin
INCDIR = /usr/local/include
LIBSDIR = /usr/local/share/hcsdk/libs
include version.mk

all clean posix linux macos win win32 dos samples_zip:
	@make --no-print-directory --silent version_$@
	$M hcasm
	$M hclink
	$M hclib
	$M hcbuild
	$M hcbcomp
	$M msxdosemu
	$M libs
	@make --no-print-directory --silent distro_$@

test: all
	$M tests

distro: all linux macos win win32 dos samples_zip
	@true

install: all
	@install -d $(INSTDIR)
	@install $(filter-out %.dSYM,$(wildcard bin/msxdosemu bin/hcasm-* bin/retrolang-* bin/hclink-* bin/hclib bin/hcbuild bin/hcbcomp-*)) $(INSTDIR)
	@install -d $(LIBSDIR)
	@install libs/*.lib $(LIBSDIR)
	@install -d $(INCDIR)
	@install include/*.b $(INCDIR)

./include/version.h: ./version.mk Makefile
	@echo "// DO NOT MODIFY; This file was automatically generated by Make." > $@
	@echo "#pragma once" >> $@
	@echo "// DO NOT MODIFY; This file was automatically generated by Make." >> $@
	@echo "#define VERSION $(VERSION)" >> $@
	@echo "// DO NOT MODIFY; This file was automatically generated by Make." >> $@
	@echo "#define SUBVERSION $(SUBVERSION)" >> $@
	@echo "// DO NOT MODIFY; This file was automatically generated by Make." >> $@
	@echo "#define REVISION $(REVISION)" >> $@

bin/dpkg/hcsdk/DEBIAN/control: ./version.mk Makefile
	@mkdir -p $(@D)
	@echo "Package: hcsdk" > $@
	@echo "Version: $(VERSION).$(SUBVERSION).$(REVISION)" >> $@
	@echo "Maintainer: Humberto Costa <humbertocsjr@github>" >> $@
	@echo "Architecture: amd64" >> $@
	@echo "Depends: libc6" >> $@
	@echo "Description: HC Software Development Kit for Retro Computing" >> $@

version_all version_posix version_test version_test_emu version_dos version_win version_win32 version_macos version_linux version_samples_zip version_clean: ./include/version.h
	@true


distro_all distro_posix distro_test distro_test_emu:
	@true

distro_samples_zip:
	@echo [ZIP] hcsdk-samples-v$(VERSION)-$(SUBVERSION)-R$(REVISION).zip
	@cd samples; zip -r ../hcsdk-samples-v$(VERSION)-$(SUBVERSION)-R$(REVISION).zip ./  > /dev/null
	@cp hcsdk-samples-v$(VERSION)-$(SUBVERSION)-R$(REVISION).zip distrosite/hcsdk-samples.zip

distro_dos:
	@mkdir -p bin/dos/
	@mv bin/dos/hcasm-8080.exe bin/dos/hcasm80.exe
	@mv bin/dos/hcasm-8085.exe bin/dos/hcasm85.exe
	@mv bin/dos/hcasm-8086.exe bin/dos/hcasm86.exe
	@mv bin/dos/hcasm-z80.exe bin/dos/hcasmz80.exe
	@mv bin/dos/hclink-bin.exe bin/dos/hclnkbin.exe
	@mv bin/dos/hclink-rex.exe bin/dos/hclnkrex.exe
	@#mv bin/dos/msxdosemu.exe bin/dos/msxdos.exe
	@mv bin/dos/hcbcomp-8086.exe bin/dos/hcb86.exe
	@mv bin/dos/hcbcomp-z80.exe bin/dos/hcbz80.exe
	@mv bin/dos/hcbcomp-8080.exe bin/dos/hcb80.exe
	@mv bin/dos/hcbcomp-8085.exe bin/dos/hcb85.exe
	@mkdir -p bin/win/include
	@cp include/*.b bin/win/include/
	@mkdir -p bin/win/libs
	@cp libs/*.lib bin/win/libs/
	@echo [ZIP] hcsdk-dos-v$(VERSION)-$(SUBVERSION)-R$(REVISION).zip
	@cd bin/dos; zip -r ../../hcsdk-dos-v$(VERSION)-$(SUBVERSION)-R$(REVISION).zip ./  > /dev/null
	@mkdir -p distrosite
	@cp hcsdk-dos-v$(VERSION)-$(SUBVERSION)-R$(REVISION).zip distrosite/hcsdk-dos.zip


distro_win:
	@mkdir -p bin/win/
	@cp distrofiles/setenv.bat bin/win/setenv.bat
	@cp distrofiles/hcsdk.ico bin/win/hcsdk.ico
	@cp distrofiles/windows.nsi bin/win/windows.nsi
	@mkdir -p bin/win/include
	@cp include/*.b bin/win/include/
	@mkdir -p bin/win/libs
	@cp libs/*.lib bin/win/libs/
	@sed -i -e "s/___VERSION___/$(VERSION).$(SUBVERSION).$(REVISION)/g" bin/win/windows.nsi
	@rm bin/win/windows.nsi-e 2>/dev/null | true
	@echo [ZIP] hcsdk-win-v$(VERSION)-$(SUBVERSION)-R$(REVISION).zip
	@rm hcsdk-win-v$(VERSION)-$(SUBVERSION)-R$(REVISION).zip 2>/dev/null | true
	@cd bin/win; zip -r ../../hcsdk-win-v$(VERSION)-$(SUBVERSION)-R$(REVISION).zip ./  > /dev/null
	@mkdir -p distrosite
	@cp hcsdk-win-v$(VERSION)-$(SUBVERSION)-R$(REVISION).zip distrosite/hcsdk-win.zip
	@echo [EXE] hcsdk-win-v$(VERSION)-$(SUBVERSION)-R$(REVISION)-setup.exe
	@cd bin/win; makensis windows.nsi > /dev/null
	@mv hcsdk-win-installer.exe hcsdk-win-v$(VERSION)-$(SUBVERSION)-R$(REVISION)-setup.exe
	@mkdir -p distrosite
	@cp hcsdk-win-v$(VERSION)-$(SUBVERSION)-R$(REVISION)-setup.exe distrosite/hcsdk-win.exe

distro_win32:
	@mkdir -p bin/win32/
	@cp distrofiles/setenv.bat bin/win32/setenv.bat
	@cp distrofiles/hcsdk.ico bin/win32/hcsdk.ico
	@cp distrofiles/windows32.nsi bin/win32/windows.nsi
	@mkdir -p bin/win32/include
	@cp include/*.b bin/win32/include/
	@mkdir -p bin/win32/libs
	@cp libs/*.lib bin/win32/libs/
	@sed -i -e "s/___VERSION___/$(VERSION).$(SUBVERSION).$(REVISION)/g" bin/win32/windows.nsi
	@rm bin/win32/windows.nsi-e 2>/dev/null | true
	@echo [ZIP] hcsdk-win32-v$(VERSION)-$(SUBVERSION)-R$(REVISION).zip
	@rm hcsdk-win32-v$(VERSION)-$(SUBVERSION)-R$(REVISION).zip 2>/dev/null | true
	@cd bin/win32; zip -r ../../hcsdk-win32-v$(VERSION)-$(SUBVERSION)-R$(REVISION).zip ./  > /dev/null
	@mkdir -p distrosite
	@cp hcsdk-win32-v$(VERSION)-$(SUBVERSION)-R$(REVISION).zip distrosite/hcsdk-win32.zip
	@echo [EXE] hcsdk-win32-v$(VERSION)-$(SUBVERSION)-R$(REVISION)-setup.exe
	@cd bin/win32; makensis windows.nsi > /dev/null
	@mv hcsdk-win-installer.exe hcsdk-win32-v$(VERSION)-$(SUBVERSION)-R$(REVISION)-setup.exe
	@mkdir -p distrosite
	@cp hcsdk-win32-v$(VERSION)-$(SUBVERSION)-R$(REVISION)-setup.exe distrosite/hcsdk-win32.exe

distro_macos:
	@echo [TGZ] hcsdk-macos-v$(VERSION)-$(SUBVERSION)-R$(REVISION).tgz
	@rm hcsdk-macos-v$(VERSION)-$(SUBVERSION)-R$(REVISION).tgz 2>/dev/null | true
	@mkdir -p bin/macos/include
	@cp include/*.b bin/macos/include/
	@mkdir -p bin/macos/libs
	@cp libs/*.lib bin/macos/libs/
	@cd bin/macos; tar -czvf ../../hcsdk-macos-v$(VERSION)-$(SUBVERSION)-R$(REVISION).tgz ./ >/dev/null 2>&1
	@mkdir -p distrosite
	@cp hcsdk-macos-v$(VERSION)-$(SUBVERSION)-R$(REVISION).tgz distrosite/hcsdk-macos.tgz
	@echo [PKG] hcsdk-macos-v$(VERSION)-$(SUBVERSION)-R$(REVISION)-setup.pkg
	@mkdir -p bin/pkg/usr/local/bin
	@cp bin/macos/hc* bin/pkg/usr/local/bin/
	@mkdir -p bin/pkg/usr/local/share/hcsdk/
	@cp bin/macos/license.txt bin/pkg/usr/local/share/hcsdk/license
	@mkdir -p bin/pkg/usr/local/share/hcsdk/samples
	@cp -R samples bin/pkg/usr/local/share/hcsdk/samples
	@mkdir -p bin/pkg/usr/local/share/hcsdk/libs
	@cp libs/*.lib bin/pkg/usr/local/share/hcsdk/libs/
	@mkdir -p bin/pkg/usr/local/include
	@cp -R include bin/pkg/usr/local/include
	@pkgbuild --ownership recommended --quiet  --root bin/pkg --install-location / --identifier br.dev.humbertocsjr.hcsdk --version $(VERSION).$(SUBVERSION).$(REVISION) hcsdk-macos-v$(VERSION)-$(SUBVERSION)-R$(REVISION)-setup.pkg
	@mkdir -p distrosite
	@cp hcsdk-macos-v$(VERSION)-$(SUBVERSION)-R$(REVISION)-setup.pkg distrosite/hcsdk-macos.pkg

distro_linux: bin/dpkg/hcsdk/DEBIAN/control
	@echo [TGZ] hcsdk-linux-v$(VERSION)-$(SUBVERSION)-R$(REVISION).tgz
	@rm hcsdk-linux-v$(VERSION)-$(SUBVERSION)-R$(REVISION).tgz 2>/dev/null | true
	@mkdir -p bin/linux/include
	@cp include/*.b bin/linux/include/
	@mkdir -p bin/linux/libs
	@cp libs/*.lib bin/linux/libs/
	@cd bin/linux; tar -czvf ../../hcsdk-linux-v$(VERSION)-$(SUBVERSION)-R$(REVISION).tgz ./ >/dev/null 2>&1
	@mkdir -p distrosite
	@cp hcsdk-linux-v$(VERSION)-$(SUBVERSION)-R$(REVISION).tgz distrosite/hcsdk-linux.tgz
	@echo [DEB] hcsdk-linux-v$(VERSION)-$(SUBVERSION)-R$(REVISION).deb
	@mkdir -p bin/dpkg/hcsdk/usr/local/bin
	@cp bin/linux/hc* bin/dpkg/hcsdk/usr/local/bin/
	@mkdir -p bin/dpkg/hcsdk/usr/local/share/hcsdk/
	@cp bin/linux/license bin/dpkg/hcsdk/usr/local/share/hcsdk/
	@mkdir -p bin/dpkg/hcsdk/usr/local/share/hcsdk/samples
	@cp -R samples bin/dpkg/hcsdk/usr/local/share/hcsdk/samples
	@mkdir -p bin/dpkg/hcsdk/usr/local/share/hcsdk/libs
	@cp libs/*.lib bin/dpkg/hcsdk/usr/local/share/hcsdk/libs/
	@mkdir -p bin/dpkg/hcsdk/usr/local/include
	@cp -R include bin/dpkg/hcsdk/usr/local/include
	@dpkg-deb --root-owner-group --build bin/dpkg/hcsdk hcsdk-linux-v$(VERSION)-$(SUBVERSION)-R$(REVISION).deb > /dev/null
	@mkdir -p distrosite
	@cp hcsdk-linux-v$(VERSION)-$(SUBVERSION)-R$(REVISION).deb distrosite/hcsdk-linux.deb

distro_clean:
	@rm hcsdk-*.tgz hcsdk-*.zip hcsdk-*.deb hcsdk-*.pkg hcsdk-*.exe 2> /dev/null | true
	@rm -R bin/* 2> /dev/null | true 