M = @make --no-print-directory --silent $@ -C
INSTDIR = /usr/local/bin
include version.mk

all clean test posix linux macos win win32 samples_zip:
	@make --no-print-directory --silent version_$@
	$M hcasm
	$M hclink
	$M hclib
	$M hcbuild
	$M retrolang
	$M tests
	@make --no-print-directory --silent distro_$@

distro: linux macos win win32 samples_zip
	@true

install: all
	@install -d $(INSTDIR)
	@install $(filter-out %.dSYM,$(wildcard bin/hcasm-* bin/hclink-* bin/hclib bin/hcbuild)) $(INSTDIR)

./include/version.h: ./version.mk Makefile
	@echo "// DO NOT MODIFY; This file was automatically generated by Make." > $@
	@echo "#pragma once" >> $@
	@echo "// DO NOT MODIFY; This file was automatically generated by Make." >> $@
	@echo "#define VERSION $(VERSION)" >> $@
	@echo "// DO NOT MODIFY; This file was automatically generated by Make." >> $@
	@echo "#define SUBVERSION $(SUBVERSION)" >> $@
	@echo "// DO NOT MODIFY; This file was automatically generated by Make." >> $@
	@echo "#define REVISION $(REVISION)" >> $@

bin/dpkg/hcsdk/DEBIAN/control: ./version.mk Makefile
	@mkdir -p $(@D)
	@echo "Package: hcsdk" > $@
	@echo "Version: $(VERSION).$(SUBVERSION).$(REVISION)" >> $@
	@echo "Maintainer: Humberto Costa <humbertocsjr@github>" >> $@
	@echo "Architecture: amd64" >> $@
	@echo "Depends: libc6" >> $@
	@echo "Description: HC Software Development Kit for Retro Computing" >> $@

version_all version_posix version_test version_win version_win32 version_macos version_linux version_samples_zip version_clean: ./include/version.h
	@true


distro_all distro_posix distro_test:
	@true

distro_samples_zip:
	@echo [ZIP] hcsdk-samples-v$(VERSION)-$(SUBVERSION)-R$(REVISION).zip
	@cd samples; zip -r ../hcsdk-samples-v$(VERSION)-$(SUBVERSION)-R$(REVISION).zip ./  > /dev/null
	@cp hcsdk-samples-v$(VERSION)-$(SUBVERSION)-R$(REVISION).zip distrosite/hcsdk-samples.zip

distro_win:
	@mkdir -p bin/win/
	@cp distrofiles/setenv.bat bin/win/setenv.bat
	@cp distrofiles/hcsdk.ico bin/win/hcsdk.ico
	@cp distrofiles/windows.nsi bin/win/windows.nsi
	@sed -i -e "s/___VERSION___/$(VERSION).$(SUBVERSION).$(REVISION)/g" bin/win/windows.nsi
	@rm bin/win/windows.nsi-e 2>/dev/null | true
	@echo [ZIP] hcsdk-win-v$(VERSION)-$(SUBVERSION)-R$(REVISION).zip
	@rm hcsdk-win-v$(VERSION)-$(SUBVERSION)-R$(REVISION).zip 2>/dev/null | true
	@cd bin/win; zip -r ../../hcsdk-win-v$(VERSION)-$(SUBVERSION)-R$(REVISION).zip ./  > /dev/null
	@mkdir -p distrosite
	@cp hcsdk-win-v$(VERSION)-$(SUBVERSION)-R$(REVISION).zip distrosite/hcsdk-win.pkg
	@echo [EXE] hcsdk-win-v$(VERSION)-$(SUBVERSION)-R$(REVISION)-setup.exe
	@cd bin/win; makensis windows.nsi > /dev/null
	@mv hcsdk-win-installer.exe hcsdk-win-v$(VERSION)-$(SUBVERSION)-R$(REVISION)-setup.exe
	@mkdir -p distrosite
	@cp hcsdk-win-v$(VERSION)-$(SUBVERSION)-R$(REVISION)-setup.exe distrosite/hcsdk-win.exe

distro_win32:
	@mkdir -p bin/win32/
	@cp distrofiles/setenv.bat bin/win32/setenv.bat
	@cp distrofiles/hcsdk.ico bin/win32/hcsdk.ico
	@cp distrofiles/windows32.nsi bin/win32/windows.nsi
	@sed -i -e "s/___VERSION___/$(VERSION).$(SUBVERSION).$(REVISION)/g" bin/win32/windows.nsi
	@rm bin/win32/windows.nsi-e 2>/dev/null | true
	@echo [ZIP] hcsdk-win32-v$(VERSION)-$(SUBVERSION)-R$(REVISION).zip
	@rm hcsdk-win32-v$(VERSION)-$(SUBVERSION)-R$(REVISION).zip 2>/dev/null | true
	@cd bin/win32; zip -r ../../hcsdk-win32-v$(VERSION)-$(SUBVERSION)-R$(REVISION).zip ./  > /dev/null
	@mkdir -p distrosite
	@cp hcsdk-win32-v$(VERSION)-$(SUBVERSION)-R$(REVISION).zip distrosite/hcsdk-win32.pkg
	@echo [EXE] hcsdk-win32-v$(VERSION)-$(SUBVERSION)-R$(REVISION)-setup.exe
	@cd bin/win32; makensis windows.nsi > /dev/null
	@mv hcsdk-win-installer.exe hcsdk-win32-v$(VERSION)-$(SUBVERSION)-R$(REVISION)-setup.exe
	@mkdir -p distrosite
	@cp hcsdk-win32-v$(VERSION)-$(SUBVERSION)-R$(REVISION)-setup.exe distrosite/hcsdk-win32.exe

distro_macos:
	@echo [TGZ] hcsdk-macos-v$(VERSION)-$(SUBVERSION)-R$(REVISION).tgz
	@rm hcsdk-macos-v$(VERSION)-$(SUBVERSION)-R$(REVISION).tgz 2>/dev/null | true
	@cd bin/macos; tar -czvf ../../hcsdk-macos-v$(VERSION)-$(SUBVERSION)-R$(REVISION).tgz ./ >/dev/null 2>&1
	@mkdir -p distrosite
	@cp hcsdk-macos-v$(VERSION)-$(SUBVERSION)-R$(REVISION).tgz distrosite/hcsdk-macos.tgz
	@echo [PKG] hcsdk-macos-v$(VERSION)-$(SUBVERSION)-R$(REVISION)-setup.pkg
	@mkdir -p bin/pkg/usr/local/bin
	@cp bin/macos/hc* bin/pkg/usr/local/bin/
	@mkdir -p bin/pkg/usr/local/shared/hcsdk/
	@cp bin/macos/license.txt bin/pkg/usr/local/shared/hcsdk/license
	@mkdir -p bin/pkg/usr/local/shared/hcsdk/samples
	@cp -R samples bin/pkg/usr/local/shared/hcsdk/samples
	@pkgbuild --ownership recommended --quiet  --root bin/pkg --install-location / --identifier br.dev.humbertocsjr.hcsdk --version $(VERSION).$(SUBVERSION).$(REVISION) hcsdk-macos-v$(VERSION)-$(SUBVERSION)-R$(REVISION)-setup.pkg
	@mkdir -p distrosite
	@cp hcsdk-macos-v$(VERSION)-$(SUBVERSION)-R$(REVISION)-setup.pkg distrosite/hcsdk-macos.pkg

distro_linux: bin/dpkg/hcsdk/DEBIAN/control
	@echo [TGZ] hcsdk-linux-v$(VERSION)-$(SUBVERSION)-R$(REVISION).tgz
	@rm hcsdk-linux-v$(VERSION)-$(SUBVERSION)-R$(REVISION).tgz 2>/dev/null | true
	@cd bin/linux; tar -czvf ../../hcsdk-linux-v$(VERSION)-$(SUBVERSION)-R$(REVISION).tgz ./ >/dev/null 2>&1
	@mkdir -p distrosite
	@cp hcsdk-linux-v$(VERSION)-$(SUBVERSION)-R$(REVISION).tgz distrosite/hcsdk-linux.tgz
	@echo [DEB] hcsdk-linux-v$(VERSION)-$(SUBVERSION)-R$(REVISION).deb
	@mkdir -p bin/dpkg/hcsdk/usr/local/bin
	@cp bin/linux/hc* bin/dpkg/hcsdk/usr/local/bin/
	@mkdir -p bin/dpkg/hcsdk/usr/local/shared/hcsdk/
	@cp bin/linux/license bin/dpkg/hcsdk/usr/local/shared/hcsdk/
	@mkdir -p bin/dpkg/hcsdk/usr/local/shared/hcsdk/samples
	@cp -R samples bin/dpkg/hcsdk/usr/local/shared/hcsdk/samples
	@dpkg-deb --root-owner-group --build bin/dpkg/hcsdk hcsdk-linux-v$(VERSION)-$(SUBVERSION)-R$(REVISION).deb > /dev/null
	@mkdir -p distrosite
	@cp hcsdk-linux-v$(VERSION)-$(SUBVERSION)-R$(REVISION).deb distrosite/hcsdk-linux.deb

distro_clean:
	@rm hcsdk-*.tgz hcsdk-*.zip hcsdk-*.deb hcsdk-*.pkg hcsdk-*.exe 2> /dev/null | true
	@rm -R bin/* 2> /dev/null | true 