M = @make --no-print-directory --silent $@ -C
INSTDIR = /usr/local/bin
include version.mk

all clean test posix linux macos win:
	@make --no-print-directory --silent version_$@
	$M hcasm
	$M hclink
	$M hclib
	$M hcbuild
	$M tests
	@make --no-print-directory --silent distro_$@

install: all
	@install -d $(INSTDIR)
	@install $(filter-out %.dSYM,$(wildcard bin/hcasm-* bin/hclink-* bin/hclib bin/hcbuild)) $(INSTDIR)

./include/version.h: ./version.mk Makefile
	@echo "// DO NOT MODIFY; This file was automatically generated by Make." > $@
	@echo "#pragma once" >> $@
	@echo "#define VERSION $(VERSION)" >> $@
	@echo "#define SUBVERSION $(SUBVERSION)" >> $@
	@echo "#define REVISION $(REVISION)" >> $@

bin/dpkg/hcsdk/DEBIAN/control: ./version.mk Makefile
	@mkdir -p $(@D)
	@echo "Package: hcsdk" > $@
	@echo "Version: $(VERSION).$(SUBVERSION).$(REVISION)" >> $@
	@echo "Maintainer: Humberto Costa <humbertocsjr@github>" >> $@
	@echo "Architecture: amd64" >> $@
	@echo "Description: HC Software Development Kit for Retro Computing" >> $@

version_all version_posix version_test version_win version_macos version_linux version_clean: ./include/version.h
	@true


distro_all distro_posix distro_test:
	@true

distro_win:
	@echo [ZIP] hcsdk-win-v$(VERSION)-$(SUBVERSION)-R$(REVISION).zip
	@rm hcsdk-win-v$(VERSION)-$(SUBVERSION)-R$(REVISION).zip 2>/dev/null | true
	@cd bin/win; zip -r ../../hcsdk-win-v$(VERSION)-$(SUBVERSION)-R$(REVISION).zip ./  > /dev/null

distro_macos:
	@echo [TGZ] hcsdk-macos-v$(VERSION)-$(SUBVERSION)-R$(REVISION).tgz
	@rm hcsdk-macos-v$(VERSION)-$(SUBVERSION)-R$(REVISION).tgz 2>/dev/null | true
	@cd bin/macos; tar -czvf ../../hcsdk-macos-v$(VERSION)-$(SUBVERSION)-R$(REVISION).tgz ./ >/dev/null 2>&1

distro_linux: bin/dpkg/hcsdk/DEBIAN/control
	@echo [TGZ] hcsdk-linux-v$(VERSION)-$(SUBVERSION)-R$(REVISION).tgz
	@rm hcsdk-linux-v$(VERSION)-$(SUBVERSION)-R$(REVISION).tgz 2>/dev/null | true
	@cd bin/linux; tar -czvf ../../hcsdk-linux-v$(VERSION)-$(SUBVERSION)-R$(REVISION).tgz ./ >/dev/null 2>&1
	@echo [DEB] hcsdk-linux-v$(VERSION)-$(SUBVERSION)-R$(REVISION).deb
	@mkdir -p bin/dpkg/hcsdk/usr/local/bin
	@cp bin/linux/hc* bin/dpkg/hcsdk/usr/local/bin/
	@mkdir -p bin/dpkg/hcsdk/usr/shared/hcsdk/
	@cp bin/linux/license bin/dpkg/hcsdk/usr/shared/hcsdk/
	@mkdir -p bin/dpkg/hcsdk/usr/shared/hcsdk/samples
	@cp -R samples bin/dpkg/hcsdk/usr/shared/hcsdk/samples
	@dpkg-deb --root-owner-group --build bin/dpkg/hcsdk hcsdk-linux-v$(VERSION)-$(SUBVERSION)-R$(REVISION).deb > /dev/null




distro_clean:
	@rm hcsdk-*.tgz hcsdk-*.zip 2> /dev/null | true
	@rm -R bin/* | true