; generated by hcbcomp-z80
; source: libs/b/atoi.b


section text
global atoi

section text
	; function atoi prologue
atoi:
	lxi h, 65530
	dad sp
	sphl
	lxi h, 0
	dad sp
	push h
	lxi h, 0
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	lxi h, 4
	dad sp
	push h
	lxi h, 1
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 0
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	pop d
	dad h
	dad d
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 45
	pop d
	mov a, l
	sub e
	jnz .L0
	mov a, h
	sbb d
	jnz .L0
	lxi h, 1
	jmp .L0_ret
.L0:
	lxi h, 0
.L1:
	; if
	mov a, h
	ora l
	jz .L2
	lxi h, 4
	dad sp
	push h
	lxi h, 0
	push h
	lxi h, 1
	pop d
	mov a, l
	sub e
	mov l, a
	mov a, h
	sbb d
	mov h, a
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	lxi h, 0
	dad sp
	push h
	lxi h, 0
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 1
	pop d
	dad d
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	jmp .L3
.L2:
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 0
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	pop d
	dad h
	dad d
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 43
	pop d
	mov a, l
	sub e
	jnz .L4
	mov a, h
	sbb d
	jnz .L4
	lxi h, 1
	jmp .L4_ret
.L4:
	lxi h, 0
.L5:
	; if
	mov a, h
	ora l
	jz .L6
	lxi h, 0
	dad sp
	push h
	lxi h, 0
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 1
	pop d
	dad d
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
.L6:
.L3:
	lxi h, 2
	dad sp
	push h
	lxi h, 0
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
.L8:
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 0
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	pop d
	dad h
	dad d
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 48
	pop d
	xchg
	mov a, l
	sub e
	mov l, a
	mov a, h
	sbb d
	mov h, a
	jc .L11
	lxi h, 1
	jmp .L11_ret
.L11:
	lxi h, 0
.L12:
	; && short-circuit
	mov a, h
	ora l
	jz .L13
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 0
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	pop d
	dad h
	dad d
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 57
	pop d
	xchg
	mov a, l
	sub e
	mov l, a
	mov a, h
	sbb d
	mov h, a
	jc .L15
	jz .L15
	lxi h, 0
	jmp .L16_done
.L15:
	lxi h, 1
.L17:
	mov a, h
	ora l
	jz .L13
	lxi h, 1
	jmp .L14
.L13:
	lxi h, 0
.L14:
	; while
	mov a, h
	ora l
	jz .L10
	lxi h, 2
	dad sp
	push h
	lxi h, 2
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 10
	pop d
	xchg
	push h
	pop b
	lxi h, 0
	mvi a, 16
.L18:
	mov a, b
	rar
	mov b, a
	mov a, c
	rar
	mov c, a
	jnc .L19
	dad d
.L19:
	xchg
	dad h
	xchg
	dcr a
	jnz .L18
	push h
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 0
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	pop d
	dad h
	dad d
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 48
	pop d
	mov a, l
	sub e
	mov l, a
	mov a, h
	sbb d
	mov h, a
	pop d
	dad d
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	lxi h, 0
	dad sp
	push h
	lxi h, 0
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 1
	pop d
	dad d
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	jmp .L8
.L10:
	lxi h, 2
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	pop d
	xchg
	push h
	pop b
	lxi h, 0
	mvi a, 16
.L20:
	mov a, b
	rar
	mov b, a
	mov a, c
	rar
	mov c, a
	jnc .L21
	dad d
.L21:
	xchg
	dad h
	xchg
	dcr a
	jnz .L20
	; return
	ret
	; function atoi epilogue
	ret
