; generated by hcbcomp-z80
; source: libs/b/itoa.b


section text
global itoa

section text
	; function itoa prologue
itoa:
	lxi h, 65526
	dad sp
	sphl
	lxi h, 0
	dad sp
	push h
	lxi h, 0
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	lxi h, 2
	dad sp
	push h
	lxi h, 0
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 0
	pop d
	xchg
	mov a, l
	sub e
	mov l, a
	mov a, h
	sbb d
	mov h, a
	jc .L0
	lxi h, 0
	jmp .L0_ret
.L0:
	lxi h, 1
.L1:
	; if
	mov a, h
	ora l
	jz .L2
	lxi h, 2
	dad sp
	push h
	lxi h, 1
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	lxi h, 4
	dad sp
	push h
	lxi h, 0
	push h
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	pop d
	mov a, l
	sub e
	mov l, a
	mov a, h
	sbb d
	mov h, a
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
.L2:
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 0
	pop d
	mov a, l
	sub e
	jnz .L4
	mov a, h
	sbb d
	jnz .L4
	lxi h, 1
	jmp .L4_ret
.L4:
	lxi h, 0
.L5:
	; if
	mov a, h
	ora l
	jz .L6
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 0
	pop d
	dad h
	dad d
	push h
	lxi h, 48
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	lxi h, 0
	dad sp
	push h
	lxi h, 1
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	jmp .L7
.L6:
.L8:
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 0
	pop d
	xchg
	mov a, l
	sub e
	mov l, a
	mov a, h
	sbb d
	mov h, a
	jc .L11
	jz .L11
	lxi h, 1
	jmp .L12_done
.L11:
	lxi h, 0
.L13:
	; while
	mov a, h
	ora l
	jz .L10
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 0
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	pop d
	dad h
	dad d
	push h
	lxi h, 48
	push h
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 10
	pop d
	xchg
	lxi b, 0
	mvi a, 16
.L14:
	dad h
	mov a, c
	ral
	mov c, a
	mov a, b
	ral
	mov b, a
	mov a, c
	sub e
	mov c, a
	mov a, b
	sbb d
	mov b, a
	jc .L15
	inx h
	jmp .L16
.L15:
	mov a, c
	add e
	mov c, a
	mov a, b
	adc d
	mov b, a
.L16:
	dcr a
	jnz .L14
	mov l, c
	mov h, b
	pop d
	dad d
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	lxi h, 4
	dad sp
	push h
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 10
	pop d
	xchg
	lxi b, 0
	mvi a, 16
.L17:
	dad h
	mov a, c
	ral
	mov c, a
	mov a, b
	ral
	mov b, a
	mov a, c
	sub e
	mov c, a
	mov a, b
	sbb d
	mov b, a
	jc .L18
	inx h
	jmp .L19
.L18:
	mov a, c
	add e
	mov c, a
	mov a, b
	adc d
	mov b, a
.L19:
	dcr a
	jnz .L17
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	lxi h, 0
	dad sp
	push h
	lxi h, 0
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 1
	pop d
	dad d
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	jmp .L8
.L10:
.L7:
	lxi h, 2
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	; if
	mov a, h
	ora l
	jz .L20
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 0
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	pop d
	dad h
	dad d
	push h
	lxi h, 45
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	lxi h, 0
	dad sp
	push h
	lxi h, 0
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 1
	pop d
	dad d
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
.L20:
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 0
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	pop d
	dad h
	dad d
	push h
	lxi h, 0
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	lxi h, 6
	dad sp
	push h
	lxi h, 0
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	lxi h, 8
	dad sp
	push h
	lxi h, 0
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 1
	pop d
	mov a, l
	sub e
	mov l, a
	mov a, h
	sbb d
	mov h, a
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	lxi h, 2
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	; if
	mov a, h
	ora l
	jz .L22
	lxi h, 8
	dad sp
	push h
	lxi h, 8
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 1
	pop d
	mov a, l
	sub e
	mov l, a
	mov a, h
	sbb d
	mov h, a
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
.L22:
.L24:
	lxi h, 6
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 8
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	pop d
	xchg
	mov a, l
	sub e
	mov l, a
	mov a, h
	sbb d
	mov h, a
	jc .L27
	lxi h, 0
	jmp .L27_ret
.L27:
	lxi h, 1
.L28:
	; while
	mov a, h
	ora l
	jz .L26
	lxi h, 4
	dad sp
	push h
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 6
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	pop d
	dad h
	dad d
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 6
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	pop d
	dad h
	dad d
	push h
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 8
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	pop d
	dad h
	dad d
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 8
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	pop d
	dad h
	dad d
	push h
	lxi h, 4
	dad sp
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	lxi h, 6
	dad sp
	push h
	lxi h, 6
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 1
	pop d
	dad d
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	lxi h, 8
	dad sp
	push h
	lxi h, 8
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 1
	pop d
	mov a, l
	sub e
	mov l, a
	mov a, h
	sbb d
	mov h, a
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	jmp .L24
.L26:
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	; return
	ret
	; function itoa epilogue
	ret
