; generated by hcbcomp-z80
; source: libs/b/printf.b


section text
extern putchar
global _print_digit

section text
	; function _print_digit prologue
_print_digit:
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 10
	pop d
	xchg
	mov a, l
	sub e
	mov l, a
	mov a, h
	sbb d
	mov h, a
	jc .L0
	lxi h, 1
	jmp .L0_ret
.L0:
	lxi h, 0
.L1:
	; if
	mov a, h
	ora l
	jz .L2
	lxi h, putchar
	; call putchar
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 10
	pop d
	mov a, l
	sub e
	mov l, a
	mov a, h
	sbb d
	mov h, a
	push h
	lxi h, 97
	pop d
	dad d
	push h
	; call putchar(1 args)
	call putchar
	lxi h, 2
	dad sp
	sphl
	jmp .L3
.L2:
	lxi h, putchar
	; call putchar
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 48
	pop d
	dad d
	push h
	; call putchar(1 args)
	call putchar
	lxi h, 2
	dad sp
	sphl
.L3:
	; function _print_digit epilogue
	ret
global _print_u

section text
	; function _print_u prologue
_print_u:
	lxi h, 65532
	dad sp
	sphl
	lxi h, 2
	dad sp
	push h
	lxi h, 0
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 0
	pop d
	mov a, l
	sub e
	jnz .L4
	mov a, h
	sbb d
	jnz .L4
	lxi h, 1
	jmp .L4_ret
.L4:
	lxi h, 0
.L5:
	; if
	mov a, h
	ora l
	jz .L6
	lxi h, 0
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 0
	pop d
	dad h
	dad d
	push h
	lxi h, 48
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	lxi h, 2
	dad sp
	push h
	lxi h, 1
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	jmp .L7
.L6:
.L8:
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 0
	pop d
	xchg
	mov a, l
	sub e
	mov l, a
	mov a, h
	sbb d
	mov h, a
	jc .L11
	jz .L11
	lxi h, 1
	jmp .L12_done
.L11:
	lxi h, 0
.L13:
	; while
	mov a, h
	ora l
	jz .L10
	lxi h, 0
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 2
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	pop d
	dad h
	dad d
	push h
	lxi h, 48
	push h
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 10
	pop d
	xchg
	lxi b, 0
	mvi a, 16
.L14:
	dad h
	mov a, c
	ral
	mov c, a
	mov a, b
	ral
	mov b, a
	mov a, c
	sub e
	mov c, a
	mov a, b
	sbb d
	mov b, a
	jc .L15
	inx h
	jmp .L16
.L15:
	mov a, c
	add e
	mov c, a
	mov a, b
	adc d
	mov b, a
.L16:
	dcr a
	jnz .L14
	mov l, c
	mov h, b
	pop d
	dad d
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	lxi h, 4
	dad sp
	push h
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 10
	pop d
	xchg
	lxi b, 0
	mvi a, 16
.L17:
	dad h
	mov a, c
	ral
	mov c, a
	mov a, b
	ral
	mov b, a
	mov a, c
	sub e
	mov c, a
	mov a, b
	sbb d
	mov b, a
	jc .L18
	inx h
	jmp .L19
.L18:
	mov a, c
	add e
	mov c, a
	mov a, b
	adc d
	mov b, a
.L19:
	dcr a
	jnz .L17
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	lxi h, 2
	dad sp
	push h
	lxi h, 2
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 1
	pop d
	dad d
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	jmp .L8
.L10:
.L7:
.L20:
	lxi h, 2
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 0
	pop d
	xchg
	mov a, l
	sub e
	mov l, a
	mov a, h
	sbb d
	mov h, a
	jc .L23
	jz .L23
	lxi h, 1
	jmp .L24_done
.L23:
	lxi h, 0
.L25:
	; while
	mov a, h
	ora l
	jz .L22
	lxi h, 2
	dad sp
	push h
	lxi h, 2
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 1
	pop d
	mov a, l
	sub e
	mov l, a
	mov a, h
	sbb d
	mov h, a
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	lxi h, putchar
	; call putchar
	lxi h, 0
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 2
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	pop d
	dad h
	dad d
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	; call putchar(1 args)
	call putchar
	lxi h, 2
	dad sp
	sphl
	jmp .L20
.L22:
	; function _print_u epilogue
	ret
global _print_s

section text
	; function _print_s prologue
_print_s:
	lxi h, 65534
	dad sp
	sphl
	lxi h, 0
	dad sp
	push h
	lxi h, 0
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
.L26:
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 0
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	pop d
	dad h
	dad d
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 0
	pop d
	mov a, l
	sub e
	jnz .L29
	mov a, h
	sbb d
	jz .L29_eq
.L29:
	lxi h, 1
	jmp .L29_ret
.L30:
	; while
	mov a, h
	ora l
	jz .L28
	lxi h, putchar
	; call putchar
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 0
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	pop d
	dad h
	dad d
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	; call putchar(1 args)
	call putchar
	lxi h, 2
	dad sp
	sphl
	lxi h, 0
	dad sp
	push h
	lxi h, 0
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 1
	pop d
	dad d
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	jmp .L26
.L28:
	; function _print_s epilogue
	ret
global _print_x

section text
	; function _print_x prologue
_print_x:
	lxi h, 65530
	dad sp
	sphl
	lxi h, 0
	dad sp
	push h
	lxi h, 0
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
.L31:
	lxi h, 0
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 4
	pop d
	xchg
	mov a, l
	sub e
	mov l, a
	mov a, h
	sbb d
	mov h, a
	jc .L34
	lxi h, 0
	jmp .L34_ret
.L34:
	lxi h, 1
.L35:
	; while
	mov a, h
	ora l
	jz .L33
	lxi h, 2
	dad sp
	push h
	lxi h, 12
	push h
	lxi h, 0
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 4
	pop d
	xchg
	push h
	pop b
	lxi h, 0
	mvi a, 16
.L36:
	mov a, b
	rar
	mov b, a
	mov a, c
	rar
	mov c, a
	jnc .L37
	dad d
.L37:
	xchg
	dad h
	xchg
	dcr a
	jnz .L36
	pop d
	mov a, l
	sub e
	mov l, a
	mov a, h
	sbb d
	mov h, a
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	lxi h, 4
	dad sp
	push h
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 2
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	pop d
	xchg
	mov a, e
	ora a
	jz .L38
.L39:
	mov a, h
	rar
	mov h, a
	mov a, l
	rar
	mov l, a
	dcr a
	jnz .L39
.L38:
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	lxi h, 4
	dad sp
	push h
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 15
	pop d
	mov a, l
	ana e
	mov l, a
	mov a, h
	ana d
	mov h, a
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
extern _print_digit
	lxi h, _print_digit
	; call _print_digit
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	; call _print_digit(1 args)
	call _print_digit
	lxi h, 2
	dad sp
	sphl
	lxi h, 0
	dad sp
	push h
	lxi h, 0
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 1
	pop d
	dad d
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	jmp .L31
.L33:
	; function _print_x epilogue
	ret
global printf

section text
	; function printf prologue
printf:
	lxi h, 65530
	dad sp
	sphl
	lxi h, 0
	dad sp
	push h
	lxi h, 0
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	lxi h, 4
	dad sp
	push h
	lxi h, 4
	dad sp
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
.L40:
	lxi h, 1
	; while
	mov a, h
	ora l
	jz .L42
	lxi h, 2
	dad sp
	push h
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 0
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	pop d
	dad h
	dad d
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	lxi h, 2
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 0
	pop d
	mov a, l
	sub e
	jnz .L43
	mov a, h
	sbb d
	jnz .L43
	lxi h, 1
	jmp .L43_ret
.L43:
	lxi h, 0
.L44:
	; if
	mov a, h
	ora l
	jz .L45
	; return
	ret
.L45:
	lxi h, 2
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 37
	pop d
	mov a, l
	sub e
	jnz .L47
	mov a, h
	sbb d
	jnz .L47
	lxi h, 1
	jmp .L47_ret
.L47:
	lxi h, 0
.L48:
	; if
	mov a, h
	ora l
	jz .L49
	lxi h, 0
	dad sp
	push h
	lxi h, 0
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 1
	pop d
	dad d
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	lxi h, 2
	dad sp
	push h
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 0
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	pop d
	dad h
	dad d
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	lxi h, 2
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 100
	pop d
	mov a, l
	sub e
	jnz .L51
	mov a, h
	sbb d
	jnz .L51
	lxi h, 1
	jmp .L51_ret
.L51:
	lxi h, 0
.L52:
	; if
	mov a, h
	ora l
	jz .L53
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 32768
	pop d
	mov a, l
	ana e
	mov l, a
	mov a, h
	ana d
	mov h, a
	; if
	mov a, h
	ora l
	jz .L55
	lxi h, putchar
	; call putchar
	lxi h, 45
	push h
	; call putchar(1 args)
	call putchar
	lxi h, 2
	dad sp
	sphl
extern _print_u
	lxi h, _print_u
	; call _print_u
	lxi h, 0
	push h
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	pop d
	mov a, l
	sub e
	mov l, a
	mov a, h
	sbb d
	mov h, a
	push h
	; call _print_u(1 args)
	call _print_u
	lxi h, 2
	dad sp
	sphl
	jmp .L56
.L55:
	lxi h, _print_u
	; call _print_u
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	; call _print_u(1 args)
	call _print_u
	lxi h, 2
	dad sp
	sphl
.L56:
	lxi h, 4
	dad sp
	push h
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 1
	pop d
	dad d
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	jmp .L54
.L53:
	lxi h, 2
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 117
	pop d
	mov a, l
	sub e
	jnz .L57
	mov a, h
	sbb d
	jnz .L57
	lxi h, 1
	jmp .L57_ret
.L57:
	lxi h, 0
.L58:
	; if
	mov a, h
	ora l
	jz .L59
	lxi h, _print_u
	; call _print_u
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	; call _print_u(1 args)
	call _print_u
	lxi h, 2
	dad sp
	sphl
	lxi h, 4
	dad sp
	push h
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 1
	pop d
	dad d
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	jmp .L60
.L59:
	lxi h, 2
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 120
	pop d
	mov a, l
	sub e
	jnz .L61
	mov a, h
	sbb d
	jnz .L61
	lxi h, 1
	jmp .L61_ret
.L61:
	lxi h, 0
.L62:
	; if
	mov a, h
	ora l
	jz .L63
extern _print_x
	lxi h, _print_x
	; call _print_x
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	; call _print_x(1 args)
	call _print_x
	lxi h, 2
	dad sp
	sphl
	lxi h, 4
	dad sp
	push h
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 1
	pop d
	dad d
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	jmp .L64
.L63:
	lxi h, 2
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 115
	pop d
	mov a, l
	sub e
	jnz .L65
	mov a, h
	sbb d
	jnz .L65
	lxi h, 1
	jmp .L65_ret
.L65:
	lxi h, 0
.L66:
	; if
	mov a, h
	ora l
	jz .L67
extern _print_s
	lxi h, _print_s
	; call _print_s
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	; call _print_s(1 args)
	call _print_s
	lxi h, 2
	dad sp
	sphl
	lxi h, 4
	dad sp
	push h
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 1
	pop d
	dad d
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	jmp .L68
.L67:
	lxi h, 2
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 99
	pop d
	mov a, l
	sub e
	jnz .L69
	mov a, h
	sbb d
	jnz .L69
	lxi h, 1
	jmp .L69_ret
.L69:
	lxi h, 0
.L70:
	; if
	mov a, h
	ora l
	jz .L71
	lxi h, putchar
	; call putchar
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	; call putchar(1 args)
	call putchar
	lxi h, 2
	dad sp
	sphl
	lxi h, 4
	dad sp
	push h
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 1
	pop d
	dad d
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	jmp .L72
.L71:
	lxi h, 2
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 37
	pop d
	mov a, l
	sub e
	jnz .L73
	mov a, h
	sbb d
	jnz .L73
	lxi h, 1
	jmp .L73_ret
.L73:
	lxi h, 0
.L74:
	; if
	mov a, h
	ora l
	jz .L75
	lxi h, putchar
	; call putchar
	lxi h, 37
	push h
	; call putchar(1 args)
	call putchar
	lxi h, 2
	dad sp
	sphl
.L75:
.L72:
.L68:
.L64:
.L60:
.L54:
	lxi h, 0
	dad sp
	push h
	lxi h, 0
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 1
	pop d
	dad d
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	jmp .L50
.L49:
	lxi h, putchar
	; call putchar
	lxi h, 2
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	; call putchar(1 args)
	call putchar
	lxi h, 2
	dad sp
	sphl
	lxi h, 0
	dad sp
	push h
	lxi h, 0
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 1
	pop d
	dad d
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
.L50:
	jmp .L40
.L42:
	; function printf epilogue
	ret
