; generated by hcbcomp-z80
; source: libs/b/strcat.b


section text
global strcat

section text
	; function strcat prologue
strcat:
	lxi h, 65532
	dad sp
	sphl
	lxi h, 0
	dad sp
	push h
	lxi h, 0
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
.L0:
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 0
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	pop d
	dad h
	dad d
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 0
	pop d
	mov a, l
	sub e
	jnz .L3
	mov a, h
	sbb d
	jz .L3_eq
.L3:
	lxi h, 1
	jmp .L3_ret
.L4:
	; while
	mov a, h
	ora l
	jz .L2
	lxi h, 0
	dad sp
	push h
	lxi h, 0
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 1
	pop d
	dad d
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	jmp .L0
.L2:
	lxi h, 2
	dad sp
	push h
	lxi h, 0
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
.L5:
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 2
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	pop d
	dad h
	dad d
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 0
	pop d
	mov a, l
	sub e
	jnz .L8
	mov a, h
	sbb d
	jz .L8_eq
.L8:
	lxi h, 1
	jmp .L8_ret
.L9:
	; while
	mov a, h
	ora l
	jz .L7
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 0
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	pop d
	dad h
	dad d
	push h
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 2
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	pop d
	dad h
	dad d
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	lxi h, 0
	dad sp
	push h
	lxi h, 0
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 1
	pop d
	dad d
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	lxi h, 2
	dad sp
	push h
	lxi h, 2
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 1
	pop d
	dad d
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	jmp .L5
.L7:
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 0
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	pop d
	dad h
	dad d
	push h
	lxi h, 0
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	; return
	ret
	; function strcat epilogue
	ret
