; generated by hcbcomp-8086
; source: abs.b


section text
global abs

section text
	; function abs prologue
abs:
	push bp
	mov bp, sp
	lea ax, [bp+4]
	mov bx, ax
	mov ax, [bx]
	push ax
	mov ax, 0
	pop bx
	cmp bx, ax
	jnl .L0
	mov ax, 1
	jmp .L1
.L0:
	mov ax, 0
.L1:
	; if
	or ax, ax
	jz .L2
	mov ax, 0
	push ax
	lea ax, [bp+4]
	mov bx, ax
	mov ax, [bx]
	pop bx
	xchg ax, bx
	sub ax, bx
	; return
	mov sp, bp
	pop bp
	ret
.L2:
	lea ax, [bp+4]
	mov bx, ax
	mov ax, [bx]
	; return
	mov sp, bp
	pop bp
	ret
	; function abs epilogue
	mov sp, bp
	pop bp
	ret
