; generated by hcbcomp-8086
; source: atoi.b


section text
global atoi

section text
	; function atoi prologue
atoi:
	push bp
	mov bp, sp
	sub sp, 6
	lea ax, [bp-2]
	push ax
	mov ax, 0
	pop bx
	mov [bx], ax
	lea ax, [bp-6]
	push ax
	mov ax, 1
	pop bx
	mov [bx], ax
	lea ax, [bp+4]
	mov bx, ax
	mov ax, [bx]
	push ax
	lea ax, [bp-2]
	mov bx, ax
	mov ax, [bx]
	pop bx
	add ax, ax
	add ax, bx
	mov bx, ax
	mov ax, [bx]
	push ax
	mov ax, 45
	pop bx
	cmp bx, ax
	jne .L0
	mov ax, 1
	jmp .L1
.L0:
	mov ax, 0
.L1:
	; if
	or ax, ax
	jz .L2
	lea ax, [bp-6]
	push ax
	mov ax, 0
	push ax
	mov ax, 1
	pop bx
	xchg ax, bx
	sub ax, bx
	pop bx
	mov [bx], ax
	lea ax, [bp-2]
	push ax
	lea ax, [bp-2]
	mov bx, ax
	mov ax, [bx]
	push ax
	mov ax, 1
	pop bx
	add ax, bx
	pop bx
	mov [bx], ax
	jmp .L3
.L2:
	lea ax, [bp+4]
	mov bx, ax
	mov ax, [bx]
	push ax
	lea ax, [bp-2]
	mov bx, ax
	mov ax, [bx]
	pop bx
	add ax, ax
	add ax, bx
	mov bx, ax
	mov ax, [bx]
	push ax
	mov ax, 43
	pop bx
	cmp bx, ax
	jne .L4
	mov ax, 1
	jmp .L5
.L4:
	mov ax, 0
.L5:
	; if
	or ax, ax
	jz .L6
	lea ax, [bp-2]
	push ax
	lea ax, [bp-2]
	mov bx, ax
	mov ax, [bx]
	push ax
	mov ax, 1
	pop bx
	add ax, bx
	pop bx
	mov [bx], ax
.L6:
.L3:
	lea ax, [bp-4]
	push ax
	mov ax, 0
	pop bx
	mov [bx], ax
.L8:
	lea ax, [bp+4]
	mov bx, ax
	mov ax, [bx]
	push ax
	lea ax, [bp-2]
	mov bx, ax
	mov ax, [bx]
	pop bx
	add ax, ax
	add ax, bx
	mov bx, ax
	mov ax, [bx]
	push ax
	mov ax, 48
	pop bx
	cmp bx, ax
	jl .L11
	mov ax, 1
	jmp .L12
.L11:
	mov ax, 0
.L12:
	; && short-circuit
	or ax, ax
	jz .L13
	lea ax, [bp+4]
	mov bx, ax
	mov ax, [bx]
	push ax
	lea ax, [bp-2]
	mov bx, ax
	mov ax, [bx]
	pop bx
	add ax, ax
	add ax, bx
	mov bx, ax
	mov ax, [bx]
	push ax
	mov ax, 57
	pop bx
	cmp bx, ax
	jg .L15
	mov ax, 1
	jmp .L16
.L15:
	mov ax, 0
.L16:
	or ax, ax
	jz .L13
	mov ax, 1
	jmp .L14
.L13:
	mov ax, 0
.L14:
	; while
	or ax, ax
	jz .L10
	lea ax, [bp-4]
	push ax
	lea ax, [bp-4]
	mov bx, ax
	mov ax, [bx]
	push ax
	mov ax, 10
	pop bx
	xchg ax, bx
	mul bx
	push ax
	lea ax, [bp+4]
	mov bx, ax
	mov ax, [bx]
	push ax
	lea ax, [bp-2]
	mov bx, ax
	mov ax, [bx]
	pop bx
	add ax, ax
	add ax, bx
	mov bx, ax
	mov ax, [bx]
	push ax
	mov ax, 48
	pop bx
	xchg ax, bx
	sub ax, bx
	pop bx
	add ax, bx
	pop bx
	mov [bx], ax
	lea ax, [bp-2]
	push ax
	lea ax, [bp-2]
	mov bx, ax
	mov ax, [bx]
	push ax
	mov ax, 1
	pop bx
	add ax, bx
	pop bx
	mov [bx], ax
	jmp .L8
.L10:
	lea ax, [bp-4]
	mov bx, ax
	mov ax, [bx]
	push ax
	lea ax, [bp-6]
	mov bx, ax
	mov ax, [bx]
	pop bx
	xchg ax, bx
	mul bx
	; return
	mov sp, bp
	pop bp
	ret
	; function atoi epilogue
	mov sp, bp
	pop bp
	ret
