; generated by hcbcomp-8086
; source: gets.b


section text
extern getchar
global gets

section text
	; function gets prologue
gets:
	push bp
	mov bp, sp
	sub sp, 4
	lea ax, [bp-2]
	push ax
	mov ax, 0
	pop bx
	mov [bx], ax
.L0:
	lea ax, [bp-2]
	mov bx, ax
	mov ax, [bx]
	push ax
	mov ax, 254
	pop bx
	cmp bx, ax
	jnl .L3
	mov ax, 1
	jmp .L4
.L3:
	mov ax, 0
.L4:
	; while
	or ax, ax
	jz .L2
	lea ax, [bp-4]
	push ax
	mov ax, getchar
	; call getchar
	; call getchar(0 args)
	call getchar
	pop bx
	mov [bx], ax
	lea ax, [bp-4]
	mov bx, ax
	mov ax, [bx]
	push ax
	mov ax, 10
	pop bx
	cmp bx, ax
	jne .L5
	mov ax, 1
	jmp .L6
.L5:
	mov ax, 0
.L6:
	; if
	or ax, ax
	jz .L7
	jmp .L2
.L7:
	lea ax, [bp-4]
	mov bx, ax
	mov ax, [bx]
	push ax
	mov ax, 13
	pop bx
	cmp bx, ax
	jne .L9
	mov ax, 1
	jmp .L10
.L9:
	mov ax, 0
.L10:
	; if
	or ax, ax
	jz .L11
	jmp .L2
.L11:
	lea ax, [bp-4]
	mov bx, ax
	mov ax, [bx]
	push ax
	mov ax, 1
	neg ax
	pop bx
	cmp bx, ax
	jne .L13
	mov ax, 1
	jmp .L14
.L13:
	mov ax, 0
.L14:
	; if
	or ax, ax
	jz .L15
	jmp .L2
.L15:
	lea ax, [bp+4]
	mov bx, ax
	mov ax, [bx]
	push ax
	lea ax, [bp-2]
	mov bx, ax
	mov ax, [bx]
	pop bx
	add ax, ax
	add ax, bx
	push ax
	lea ax, [bp-4]
	pop bx
	mov [bx], ax
	lea ax, [bp-2]
	push ax
	lea ax, [bp-2]
	mov bx, ax
	mov ax, [bx]
	push ax
	mov ax, 1
	pop bx
	add ax, bx
	pop bx
	mov [bx], ax
	jmp .L0
.L2:
	lea ax, [bp+4]
	mov bx, ax
	mov ax, [bx]
	push ax
	lea ax, [bp-2]
	mov bx, ax
	mov ax, [bx]
	pop bx
	add ax, ax
	add ax, bx
	push ax
	mov ax, 0
	pop bx
	mov [bx], ax
	lea ax, [bp-2]
	mov bx, ax
	mov ax, [bx]
	; return
	mov sp, bp
	pop bp
	ret
	; function gets epilogue
	mov sp, bp
	pop bp
	ret
