; generated by hcbcomp-8086
; source: itoa.b


section text
global itoa

section text
	; function itoa prologue
itoa:
	push bp
	mov bp, sp
	sub sp, 10
	lea ax, [bp-2]
	push ax
	mov ax, 0
	pop bx
	mov [bx], ax
	lea ax, [bp-4]
	push ax
	mov ax, 0
	pop bx
	mov [bx], ax
	lea ax, [bp+4]
	mov bx, ax
	mov ax, [bx]
	push ax
	mov ax, 0
	pop bx
	cmp bx, ax
	jnl .L0
	mov ax, 1
	jmp .L1
.L0:
	mov ax, 0
.L1:
	; if
	or ax, ax
	jz .L2
	lea ax, [bp-4]
	push ax
	mov ax, 1
	pop bx
	mov [bx], ax
	lea ax, [bp+4]
	push ax
	mov ax, 0
	push ax
	lea ax, [bp+4]
	mov bx, ax
	mov ax, [bx]
	pop bx
	xchg ax, bx
	sub ax, bx
	pop bx
	mov [bx], ax
.L2:
	lea ax, [bp+4]
	mov bx, ax
	mov ax, [bx]
	push ax
	mov ax, 0
	pop bx
	cmp bx, ax
	jne .L4
	mov ax, 1
	jmp .L5
.L4:
	mov ax, 0
.L5:
	; if
	or ax, ax
	jz .L6
	lea ax, [bp+4]
	mov bx, ax
	mov ax, [bx]
	push ax
	mov ax, 0
	pop bx
	add ax, ax
	add ax, bx
	push ax
	mov ax, 48
	pop bx
	mov [bx], ax
	lea ax, [bp-2]
	push ax
	mov ax, 1
	pop bx
	mov [bx], ax
	jmp .L7
.L6:
.L8:
	lea ax, [bp+4]
	mov bx, ax
	mov ax, [bx]
	push ax
	mov ax, 0
	pop bx
	cmp bx, ax
	jng .L11
	mov ax, 1
	jmp .L12
.L11:
	mov ax, 0
.L12:
	; while
	or ax, ax
	jz .L10
	lea ax, [bp+4]
	mov bx, ax
	mov ax, [bx]
	push ax
	lea ax, [bp-2]
	mov bx, ax
	mov ax, [bx]
	pop bx
	add ax, ax
	add ax, bx
	push ax
	mov ax, 48
	push ax
	lea ax, [bp+4]
	mov bx, ax
	mov ax, [bx]
	push ax
	mov ax, 10
	pop bx
	xchg ax, bx
	cwd
	div bx
	mov ax, dx
	pop bx
	add ax, bx
	pop bx
	mov [bx], ax
	lea ax, [bp+4]
	push ax
	lea ax, [bp+4]
	mov bx, ax
	mov ax, [bx]
	push ax
	mov ax, 10
	pop bx
	xchg ax, bx
	cwd
	div bx
	pop bx
	mov [bx], ax
	lea ax, [bp-2]
	push ax
	lea ax, [bp-2]
	mov bx, ax
	mov ax, [bx]
	push ax
	mov ax, 1
	pop bx
	add ax, bx
	pop bx
	mov [bx], ax
	jmp .L8
.L10:
.L7:
	lea ax, [bp-4]
	mov bx, ax
	mov ax, [bx]
	; if
	or ax, ax
	jz .L13
	lea ax, [bp+4]
	mov bx, ax
	mov ax, [bx]
	push ax
	lea ax, [bp-2]
	mov bx, ax
	mov ax, [bx]
	pop bx
	add ax, ax
	add ax, bx
	push ax
	mov ax, 45
	pop bx
	mov [bx], ax
	lea ax, [bp-2]
	push ax
	lea ax, [bp-2]
	mov bx, ax
	mov ax, [bx]
	push ax
	mov ax, 1
	pop bx
	add ax, bx
	pop bx
	mov [bx], ax
.L13:
	lea ax, [bp+4]
	mov bx, ax
	mov ax, [bx]
	push ax
	lea ax, [bp-2]
	mov bx, ax
	mov ax, [bx]
	pop bx
	add ax, ax
	add ax, bx
	push ax
	mov ax, 0
	pop bx
	mov [bx], ax
	lea ax, [bp-8]
	push ax
	mov ax, 0
	pop bx
	mov [bx], ax
	lea ax, [bp-10]
	push ax
	lea ax, [bp-2]
	mov bx, ax
	mov ax, [bx]
	push ax
	mov ax, 1
	pop bx
	xchg ax, bx
	sub ax, bx
	pop bx
	mov [bx], ax
	lea ax, [bp-4]
	mov bx, ax
	mov ax, [bx]
	; if
	or ax, ax
	jz .L15
	lea ax, [bp-10]
	push ax
	lea ax, [bp-10]
	mov bx, ax
	mov ax, [bx]
	push ax
	mov ax, 1
	pop bx
	xchg ax, bx
	sub ax, bx
	pop bx
	mov [bx], ax
.L15:
.L17:
	lea ax, [bp-8]
	mov bx, ax
	mov ax, [bx]
	push ax
	lea ax, [bp-10]
	mov bx, ax
	mov ax, [bx]
	pop bx
	cmp bx, ax
	jnl .L20
	mov ax, 1
	jmp .L21
.L20:
	mov ax, 0
.L21:
	; while
	or ax, ax
	jz .L19
	lea ax, [bp-6]
	push ax
	lea ax, [bp+4]
	mov bx, ax
	mov ax, [bx]
	push ax
	lea ax, [bp-8]
	mov bx, ax
	mov ax, [bx]
	pop bx
	add ax, ax
	add ax, bx
	pop bx
	mov [bx], ax
	lea ax, [bp+4]
	mov bx, ax
	mov ax, [bx]
	push ax
	lea ax, [bp-8]
	mov bx, ax
	mov ax, [bx]
	pop bx
	add ax, ax
	add ax, bx
	push ax
	lea ax, [bp+4]
	mov bx, ax
	mov ax, [bx]
	push ax
	lea ax, [bp-10]
	mov bx, ax
	mov ax, [bx]
	pop bx
	add ax, ax
	add ax, bx
	pop bx
	mov [bx], ax
	lea ax, [bp+4]
	mov bx, ax
	mov ax, [bx]
	push ax
	lea ax, [bp-10]
	mov bx, ax
	mov ax, [bx]
	pop bx
	add ax, ax
	add ax, bx
	push ax
	lea ax, [bp-6]
	pop bx
	mov [bx], ax
	lea ax, [bp-8]
	push ax
	lea ax, [bp-8]
	mov bx, ax
	mov ax, [bx]
	push ax
	mov ax, 1
	pop bx
	add ax, bx
	pop bx
	mov [bx], ax
	lea ax, [bp-10]
	push ax
	lea ax, [bp-10]
	mov bx, ax
	mov ax, [bx]
	push ax
	mov ax, 1
	pop bx
	xchg ax, bx
	sub ax, bx
	pop bx
	mov [bx], ax
	jmp .L17
.L19:
	lea ax, [bp+4]
	mov bx, ax
	mov ax, [bx]
	; return
	mov sp, bp
	pop bp
	ret
	; function itoa epilogue
	mov sp, bp
	pop bp
	ret
