; generated by hcbcomp-8086
; source: printf.b


section text
extern putchar
global _print_digit

section text
	; function _print_digit prologue
_print_digit:
	push bp
	mov bp, sp
	lea ax, [bp+4]
	mov bx, ax
	mov ax, [bx]
	push ax
	mov ax, 10
	pop bx
	cmp bx, ax
	jl .L0
	mov ax, 1
	jmp .L1
.L0:
	mov ax, 0
.L1:
	; if
	or ax, ax
	jz .L2
	mov ax, putchar
	; call putchar
	lea ax, [bp+4]
	mov bx, ax
	mov ax, [bx]
	push ax
	mov ax, 10
	pop bx
	xchg ax, bx
	sub ax, bx
	push ax
	mov ax, 97
	pop bx
	add ax, bx
	push ax
	; call putchar(1 args)
	call putchar
	add sp, 2
	jmp .L3
.L2:
	mov ax, putchar
	; call putchar
	lea ax, [bp+4]
	mov bx, ax
	mov ax, [bx]
	push ax
	mov ax, 48
	pop bx
	add ax, bx
	push ax
	; call putchar(1 args)
	call putchar
	add sp, 2
.L3:
	; function _print_digit epilogue
	mov sp, bp
	pop bp
	ret
global _print_u

section text
	; function _print_u prologue
_print_u:
	push bp
	mov bp, sp
	sub sp, 4
	lea ax, [bp-4]
	push ax
	mov ax, 0
	pop bx
	mov [bx], ax
	lea ax, [bp+4]
	mov bx, ax
	mov ax, [bx]
	push ax
	mov ax, 0
	pop bx
	cmp bx, ax
	jne .L4
	mov ax, 1
	jmp .L5
.L4:
	mov ax, 0
.L5:
	; if
	or ax, ax
	jz .L6
	lea ax, [bp-2]
	mov bx, ax
	mov ax, [bx]
	push ax
	mov ax, 0
	pop bx
	add ax, ax
	add ax, bx
	push ax
	mov ax, 48
	pop bx
	mov [bx], ax
	lea ax, [bp-4]
	push ax
	mov ax, 1
	pop bx
	mov [bx], ax
	jmp .L7
.L6:
.L8:
	lea ax, [bp+4]
	mov bx, ax
	mov ax, [bx]
	push ax
	mov ax, 0
	pop bx
	cmp bx, ax
	jng .L11
	mov ax, 1
	jmp .L12
.L11:
	mov ax, 0
.L12:
	; while
	or ax, ax
	jz .L10
	lea ax, [bp-2]
	mov bx, ax
	mov ax, [bx]
	push ax
	lea ax, [bp-4]
	mov bx, ax
	mov ax, [bx]
	pop bx
	add ax, ax
	add ax, bx
	push ax
	mov ax, 48
	push ax
	lea ax, [bp+4]
	mov bx, ax
	mov ax, [bx]
	push ax
	mov ax, 10
	pop bx
	xchg ax, bx
	cwd
	div bx
	mov ax, dx
	pop bx
	add ax, bx
	pop bx
	mov [bx], ax
	lea ax, [bp+4]
	push ax
	lea ax, [bp+4]
	mov bx, ax
	mov ax, [bx]
	push ax
	mov ax, 10
	pop bx
	xchg ax, bx
	cwd
	div bx
	pop bx
	mov [bx], ax
	lea ax, [bp-4]
	push ax
	lea ax, [bp-4]
	mov bx, ax
	mov ax, [bx]
	push ax
	mov ax, 1
	pop bx
	add ax, bx
	pop bx
	mov [bx], ax
	jmp .L8
.L10:
.L7:
.L13:
	lea ax, [bp-4]
	mov bx, ax
	mov ax, [bx]
	push ax
	mov ax, 0
	pop bx
	cmp bx, ax
	jng .L16
	mov ax, 1
	jmp .L17
.L16:
	mov ax, 0
.L17:
	; while
	or ax, ax
	jz .L15
	lea ax, [bp-4]
	push ax
	lea ax, [bp-4]
	mov bx, ax
	mov ax, [bx]
	push ax
	mov ax, 1
	pop bx
	xchg ax, bx
	sub ax, bx
	pop bx
	mov [bx], ax
	mov ax, putchar
	; call putchar
	lea ax, [bp-2]
	mov bx, ax
	mov ax, [bx]
	push ax
	lea ax, [bp-4]
	mov bx, ax
	mov ax, [bx]
	pop bx
	add ax, ax
	add ax, bx
	mov bx, ax
	mov ax, [bx]
	push ax
	; call putchar(1 args)
	call putchar
	add sp, 2
	jmp .L13
.L15:
	; function _print_u epilogue
	mov sp, bp
	pop bp
	ret
global _print_s

section text
	; function _print_s prologue
_print_s:
	push bp
	mov bp, sp
	sub sp, 2
	lea ax, [bp-2]
	push ax
	mov ax, 0
	pop bx
	mov [bx], ax
.L18:
	lea ax, [bp+4]
	mov bx, ax
	mov ax, [bx]
	push ax
	lea ax, [bp-2]
	mov bx, ax
	mov ax, [bx]
	pop bx
	add ax, ax
	add ax, bx
	mov bx, ax
	mov ax, [bx]
	push ax
	mov ax, 0
	pop bx
	cmp bx, ax
	je .L21
	mov ax, 1
	jmp .L22
.L21:
	mov ax, 0
.L22:
	; while
	or ax, ax
	jz .L20
	mov ax, putchar
	; call putchar
	lea ax, [bp+4]
	mov bx, ax
	mov ax, [bx]
	push ax
	lea ax, [bp-2]
	mov bx, ax
	mov ax, [bx]
	pop bx
	add ax, ax
	add ax, bx
	mov bx, ax
	mov ax, [bx]
	push ax
	; call putchar(1 args)
	call putchar
	add sp, 2
	lea ax, [bp-2]
	push ax
	lea ax, [bp-2]
	mov bx, ax
	mov ax, [bx]
	push ax
	mov ax, 1
	pop bx
	add ax, bx
	pop bx
	mov [bx], ax
	jmp .L18
.L20:
	; function _print_s epilogue
	mov sp, bp
	pop bp
	ret
global _print_x

section text
	; function _print_x prologue
_print_x:
	push bp
	mov bp, sp
	sub sp, 6
	lea ax, [bp-2]
	push ax
	mov ax, 0
	pop bx
	mov [bx], ax
.L23:
	lea ax, [bp-2]
	mov bx, ax
	mov ax, [bx]
	push ax
	mov ax, 4
	pop bx
	cmp bx, ax
	jnl .L26
	mov ax, 1
	jmp .L27
.L26:
	mov ax, 0
.L27:
	; while
	or ax, ax
	jz .L25
	lea ax, [bp-4]
	push ax
	mov ax, 12
	push ax
	lea ax, [bp-2]
	mov bx, ax
	mov ax, [bx]
	push ax
	mov ax, 4
	pop bx
	xchg ax, bx
	mul bx
	pop bx
	xchg ax, bx
	sub ax, bx
	pop bx
	mov [bx], ax
	lea ax, [bp-6]
	push ax
	lea ax, [bp+4]
	mov bx, ax
	mov ax, [bx]
	push ax
	lea ax, [bp-4]
	mov bx, ax
	mov ax, [bx]
	pop bx
	xchg ax, bx
	mov cx, ax
	or cx, cx
	jz .L29
.L28:
	shr bx, 1
	dec cx
	jnz .L28
.L29:
	mov ax, bx
	pop bx
	mov [bx], ax
	lea ax, [bp-6]
	push ax
	lea ax, [bp-6]
	mov bx, ax
	mov ax, [bx]
	push ax
	mov ax, 15
	pop bx
	and ax, bx
	pop bx
	mov [bx], ax
extern _print_digit
	mov ax, _print_digit
	; call _print_digit
	lea ax, [bp-6]
	mov bx, ax
	mov ax, [bx]
	push ax
	; call _print_digit(1 args)
	call _print_digit
	add sp, 2
	lea ax, [bp-2]
	push ax
	lea ax, [bp-2]
	mov bx, ax
	mov ax, [bx]
	push ax
	mov ax, 1
	pop bx
	add ax, bx
	pop bx
	mov [bx], ax
	jmp .L23
.L25:
	; function _print_x epilogue
	mov sp, bp
	pop bp
	ret
global printf

section text
	; function printf prologue
printf:
	push bp
	mov bp, sp
	sub sp, 6
	lea ax, [bp-2]
	push ax
	mov ax, 0
	pop bx
	mov [bx], ax
	lea ax, [bp-6]
	push ax
	lea ax, [bp+4]
	pop bx
	mov [bx], ax
.L30:
	mov ax, 1
	; while
	or ax, ax
	jz .L32
	lea ax, [bp-4]
	push ax
	lea ax, [bp+4]
	mov bx, ax
	mov ax, [bx]
	push ax
	lea ax, [bp-2]
	mov bx, ax
	mov ax, [bx]
	pop bx
	add ax, ax
	add ax, bx
	pop bx
	mov [bx], ax
	lea ax, [bp-4]
	mov bx, ax
	mov ax, [bx]
	push ax
	mov ax, 0
	pop bx
	cmp bx, ax
	jne .L33
	mov ax, 1
	jmp .L34
.L33:
	mov ax, 0
.L34:
	; if
	or ax, ax
	jz .L35
	; return
	mov sp, bp
	pop bp
	ret
.L35:
	lea ax, [bp-4]
	mov bx, ax
	mov ax, [bx]
	push ax
	mov ax, 37
	pop bx
	cmp bx, ax
	jne .L37
	mov ax, 1
	jmp .L38
.L37:
	mov ax, 0
.L38:
	; if
	or ax, ax
	jz .L39
	lea ax, [bp-2]
	push ax
	lea ax, [bp-2]
	mov bx, ax
	mov ax, [bx]
	push ax
	mov ax, 1
	pop bx
	add ax, bx
	pop bx
	mov [bx], ax
	lea ax, [bp-4]
	push ax
	lea ax, [bp+4]
	mov bx, ax
	mov ax, [bx]
	push ax
	lea ax, [bp-2]
	mov bx, ax
	mov ax, [bx]
	pop bx
	add ax, ax
	add ax, bx
	pop bx
	mov [bx], ax
	lea ax, [bp-4]
	mov bx, ax
	mov ax, [bx]
	push ax
	mov ax, 100
	pop bx
	cmp bx, ax
	jne .L41
	mov ax, 1
	jmp .L42
.L41:
	mov ax, 0
.L42:
	; if
	or ax, ax
	jz .L43
	lea ax, [bp-6]
	mov bx, ax
	mov ax, [bx]
	push ax
	mov ax, 32768
	pop bx
	and ax, bx
	; if
	or ax, ax
	jz .L45
	mov ax, putchar
	; call putchar
	mov ax, 45
	push ax
	; call putchar(1 args)
	call putchar
	add sp, 2
extern _print_u
	mov ax, _print_u
	; call _print_u
	mov ax, 0
	push ax
	lea ax, [bp-6]
	mov bx, ax
	mov ax, [bx]
	pop bx
	xchg ax, bx
	sub ax, bx
	push ax
	; call _print_u(1 args)
	call _print_u
	add sp, 2
	jmp .L46
.L45:
	mov ax, _print_u
	; call _print_u
	lea ax, [bp-6]
	mov bx, ax
	mov ax, [bx]
	push ax
	; call _print_u(1 args)
	call _print_u
	add sp, 2
.L46:
	lea ax, [bp-6]
	push ax
	lea ax, [bp-6]
	mov bx, ax
	mov ax, [bx]
	push ax
	mov ax, 1
	pop bx
	add ax, bx
	pop bx
	mov [bx], ax
	jmp .L44
.L43:
	lea ax, [bp-4]
	mov bx, ax
	mov ax, [bx]
	push ax
	mov ax, 117
	pop bx
	cmp bx, ax
	jne .L47
	mov ax, 1
	jmp .L48
.L47:
	mov ax, 0
.L48:
	; if
	or ax, ax
	jz .L49
	mov ax, _print_u
	; call _print_u
	lea ax, [bp-6]
	mov bx, ax
	mov ax, [bx]
	push ax
	; call _print_u(1 args)
	call _print_u
	add sp, 2
	lea ax, [bp-6]
	push ax
	lea ax, [bp-6]
	mov bx, ax
	mov ax, [bx]
	push ax
	mov ax, 1
	pop bx
	add ax, bx
	pop bx
	mov [bx], ax
	jmp .L50
.L49:
	lea ax, [bp-4]
	mov bx, ax
	mov ax, [bx]
	push ax
	mov ax, 120
	pop bx
	cmp bx, ax
	jne .L51
	mov ax, 1
	jmp .L52
.L51:
	mov ax, 0
.L52:
	; if
	or ax, ax
	jz .L53
extern _print_x
	mov ax, _print_x
	; call _print_x
	lea ax, [bp-6]
	mov bx, ax
	mov ax, [bx]
	push ax
	; call _print_x(1 args)
	call _print_x
	add sp, 2
	lea ax, [bp-6]
	push ax
	lea ax, [bp-6]
	mov bx, ax
	mov ax, [bx]
	push ax
	mov ax, 1
	pop bx
	add ax, bx
	pop bx
	mov [bx], ax
	jmp .L54
.L53:
	lea ax, [bp-4]
	mov bx, ax
	mov ax, [bx]
	push ax
	mov ax, 115
	pop bx
	cmp bx, ax
	jne .L55
	mov ax, 1
	jmp .L56
.L55:
	mov ax, 0
.L56:
	; if
	or ax, ax
	jz .L57
extern _print_s
	mov ax, _print_s
	; call _print_s
	lea ax, [bp-6]
	mov bx, ax
	mov ax, [bx]
	push ax
	; call _print_s(1 args)
	call _print_s
	add sp, 2
	lea ax, [bp-6]
	push ax
	lea ax, [bp-6]
	mov bx, ax
	mov ax, [bx]
	push ax
	mov ax, 1
	pop bx
	add ax, bx
	pop bx
	mov [bx], ax
	jmp .L58
.L57:
	lea ax, [bp-4]
	mov bx, ax
	mov ax, [bx]
	push ax
	mov ax, 99
	pop bx
	cmp bx, ax
	jne .L59
	mov ax, 1
	jmp .L60
.L59:
	mov ax, 0
.L60:
	; if
	or ax, ax
	jz .L61
	mov ax, putchar
	; call putchar
	lea ax, [bp-6]
	mov bx, ax
	mov ax, [bx]
	push ax
	; call putchar(1 args)
	call putchar
	add sp, 2
	lea ax, [bp-6]
	push ax
	lea ax, [bp-6]
	mov bx, ax
	mov ax, [bx]
	push ax
	mov ax, 1
	pop bx
	add ax, bx
	pop bx
	mov [bx], ax
	jmp .L62
.L61:
	lea ax, [bp-4]
	mov bx, ax
	mov ax, [bx]
	push ax
	mov ax, 37
	pop bx
	cmp bx, ax
	jne .L63
	mov ax, 1
	jmp .L64
.L63:
	mov ax, 0
.L64:
	; if
	or ax, ax
	jz .L65
	mov ax, putchar
	; call putchar
	mov ax, 37
	push ax
	; call putchar(1 args)
	call putchar
	add sp, 2
.L65:
.L62:
.L58:
.L54:
.L50:
.L44:
	lea ax, [bp-2]
	push ax
	lea ax, [bp-2]
	mov bx, ax
	mov ax, [bx]
	push ax
	mov ax, 1
	pop bx
	add ax, bx
	pop bx
	mov [bx], ax
	jmp .L40
.L39:
	mov ax, putchar
	; call putchar
	lea ax, [bp-4]
	mov bx, ax
	mov ax, [bx]
	push ax
	; call putchar(1 args)
	call putchar
	add sp, 2
	lea ax, [bp-2]
	push ax
	lea ax, [bp-2]
	mov bx, ax
	mov ax, [bx]
	push ax
	mov ax, 1
	pop bx
	add ax, bx
	pop bx
	mov [bx], ax
.L40:
	jmp .L30
.L32:
	; function printf epilogue
	mov sp, bp
	pop bp
	ret
