; generated by hcbcomp-8086
; source: strcmp.b


section text
global strcmp

section text
	; function strcmp prologue
strcmp:
	push bp
	mov bp, sp
	sub sp, 2
	lea ax, [bp-2]
	push ax
	mov ax, 0
	pop bx
	mov [bx], ax
.L0:
	mov ax, 1
	; while
	or ax, ax
	jz .L2
	lea ax, [bp+4]
	mov bx, ax
	mov ax, [bx]
	push ax
	lea ax, [bp-2]
	mov bx, ax
	mov ax, [bx]
	pop bx
	add ax, ax
	add ax, bx
	mov bx, ax
	mov ax, [bx]
	push ax
	lea ax, [bp+4]
	mov bx, ax
	mov ax, [bx]
	push ax
	lea ax, [bp-2]
	mov bx, ax
	mov ax, [bx]
	pop bx
	add ax, ax
	add ax, bx
	mov bx, ax
	mov ax, [bx]
	pop bx
	cmp bx, ax
	je .L3
	mov ax, 1
	jmp .L4
.L3:
	mov ax, 0
.L4:
	; if
	or ax, ax
	jz .L5
	lea ax, [bp+4]
	mov bx, ax
	mov ax, [bx]
	push ax
	lea ax, [bp-2]
	mov bx, ax
	mov ax, [bx]
	pop bx
	add ax, ax
	add ax, bx
	mov bx, ax
	mov ax, [bx]
	push ax
	lea ax, [bp+4]
	mov bx, ax
	mov ax, [bx]
	push ax
	lea ax, [bp-2]
	mov bx, ax
	mov ax, [bx]
	pop bx
	add ax, ax
	add ax, bx
	mov bx, ax
	mov ax, [bx]
	pop bx
	cmp bx, ax
	jnl .L7
	mov ax, 1
	jmp .L8
.L7:
	mov ax, 0
.L8:
	; if
	or ax, ax
	jz .L9
	mov ax, 1
	neg ax
	; return
	mov sp, bp
	pop bp
	ret
.L9:
	mov ax, 1
	; return
	mov sp, bp
	pop bp
	ret
.L5:
	lea ax, [bp+4]
	mov bx, ax
	mov ax, [bx]
	push ax
	lea ax, [bp-2]
	mov bx, ax
	mov ax, [bx]
	pop bx
	add ax, ax
	add ax, bx
	mov bx, ax
	mov ax, [bx]
	push ax
	mov ax, 0
	pop bx
	cmp bx, ax
	jne .L11
	mov ax, 1
	jmp .L12
.L11:
	mov ax, 0
.L12:
	; if
	or ax, ax
	jz .L13
	mov ax, 0
	; return
	mov sp, bp
	pop bp
	ret
.L13:
	lea ax, [bp-2]
	push ax
	lea ax, [bp-2]
	mov bx, ax
	mov ax, [bx]
	push ax
	mov ax, 1
	pop bx
	add ax, bx
	pop bx
	mov [bx], ax
	jmp .L0
.L2:
	; function strcmp epilogue
	mov sp, bp
	pop bp
	ret
