; generated by hcbcomp-8086
; source: strcat.b


section text
global strcat

section text
	; function strcat prologue
strcat:
	push bp
	mov bp, sp
	sub sp, 4
	lea ax, [bp-2]
	push ax
	mov ax, 0
	pop bx
	mov [bx], ax
.L0:
	lea ax, [bp+4]
	mov bx, ax
	mov ax, [bx]
	push ax
	lea ax, [bp-2]
	mov bx, ax
	mov ax, [bx]
	pop bx
	add ax, ax
	add ax, bx
	mov bx, ax
	mov ax, [bx]
	push ax
	mov ax, 0
	pop bx
	cmp bx, ax
	je .L3
	mov ax, 1
	jmp .L4
.L3:
	mov ax, 0
.L4:
	; while
	or ax, ax
	jz .L2
	lea ax, [bp-2]
	push ax
	lea ax, [bp-2]
	mov bx, ax
	mov ax, [bx]
	push ax
	mov ax, 1
	pop bx
	add ax, bx
	pop bx
	mov [bx], ax
	jmp .L0
.L2:
	lea ax, [bp-4]
	push ax
	mov ax, 0
	pop bx
	mov [bx], ax
.L5:
	lea ax, [bp+4]
	mov bx, ax
	mov ax, [bx]
	push ax
	lea ax, [bp-4]
	mov bx, ax
	mov ax, [bx]
	pop bx
	add ax, ax
	add ax, bx
	mov bx, ax
	mov ax, [bx]
	push ax
	mov ax, 0
	pop bx
	cmp bx, ax
	je .L8
	mov ax, 1
	jmp .L9
.L8:
	mov ax, 0
.L9:
	; while
	or ax, ax
	jz .L7
	lea ax, [bp+4]
	mov bx, ax
	mov ax, [bx]
	push ax
	lea ax, [bp-2]
	mov bx, ax
	mov ax, [bx]
	pop bx
	add ax, ax
	add ax, bx
	push ax
	lea ax, [bp+4]
	mov bx, ax
	mov ax, [bx]
	push ax
	lea ax, [bp-4]
	mov bx, ax
	mov ax, [bx]
	pop bx
	add ax, ax
	add ax, bx
	pop bx
	mov [bx], ax
	lea ax, [bp-2]
	push ax
	lea ax, [bp-2]
	mov bx, ax
	mov ax, [bx]
	push ax
	mov ax, 1
	pop bx
	add ax, bx
	pop bx
	mov [bx], ax
	lea ax, [bp-4]
	push ax
	lea ax, [bp-4]
	mov bx, ax
	mov ax, [bx]
	push ax
	mov ax, 1
	pop bx
	add ax, bx
	pop bx
	mov [bx], ax
	jmp .L5
.L7:
	lea ax, [bp+4]
	mov bx, ax
	mov ax, [bx]
	push ax
	lea ax, [bp-2]
	mov bx, ax
	mov ax, [bx]
	pop bx
	add ax, ax
	add ax, bx
	push ax
	mov ax, 0
	pop bx
	mov [bx], ax
	lea ax, [bp+4]
	mov bx, ax
	mov ax, [bx]
	; return
	mov sp, bp
	pop bp
	ret
	; function strcat epilogue
	mov sp, bp
	pop bp
	ret
