; generated by hcbcomp-8080
; source: abs.b


section text
global abs

section text
	; function abs prologue
abs:
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 0
	pop d
	xchg
	mov a, l
	sub e
	mov l, a
	mov a, h
	sbb d
	mov h, a
	jc .L0
	lxi h, 0
	jmp .L1
.L0:
	lxi h, 1
.L1:
	; if
	mov a, h
	ora l
	jz .L2
	lxi h, 0
	push h
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	pop d
	xchg
	mov a, e
	sub l
	mov l, a
	mov a, d
	sbb h
	mov h, a
	; return
	ret
.L2:
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	; return
	ret
	; function abs epilogue
	ret
