; generated by hcbcomp-8080
; source: itoa.b


section text
global itoa

section text
	; function itoa prologue
itoa:
	lxi h, 65526
	dad sp
	sphl
	lxi h, 0
	dad sp
	push h
	lxi h, 0
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	lxi h, 2
	dad sp
	push h
	lxi h, 0
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 0
	pop d
	xchg
	mov a, l
	sub e
	mov l, a
	mov a, h
	sbb d
	mov h, a
	jc .L0
	lxi h, 0
	jmp .L1
.L0:
	lxi h, 1
.L1:
	; if
	mov a, h
	ora l
	jz .L2
	lxi h, 2
	dad sp
	push h
	lxi h, 1
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	lxi h, 4
	dad sp
	push h
	lxi h, 0
	push h
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	pop d
	xchg
	mov a, e
	sub l
	mov l, a
	mov a, d
	sbb h
	mov h, a
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
.L2:
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 0
	pop d
	mov a, l
	sub e
	jnz .L4
	mov a, h
	sbb d
	jnz .L4
	lxi h, 1
	jmp .L5
.L4:
	lxi h, 0
.L5:
	; if
	mov a, h
	ora l
	jz .L6
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 0
	pop d
	dad h
	dad d
	push h
	lxi h, 48
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	lxi h, 0
	dad sp
	push h
	lxi h, 1
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	jmp .L7
.L6:
.L8:
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 0
	pop d
	xchg
	mov a, l
	sub e
	mov l, a
	mov a, h
	sbb d
	mov h, a
	jc .L11
	jz .L11
	lxi h, 1
	jmp .L12
.L11:
	lxi h, 0
.L12:
	; while
	mov a, h
	ora l
	jz .L10
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 0
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	pop d
	dad h
	dad d
	push h
	lxi h, 48
	push h
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 10
	pop d
	xchg
	lxi b, 0
	mvi a, 16
.L13:
	push psw
	dad h
	mov a, c
	ral
	mov c, a
	mov a, b
	ral
	mov b, a
	mov a, c
	sub e
	mov c, a
	mov a, b
	sbb d
	mov b, a
	jc .L14
	inx h
	jmp .L15
.L14:
	mov a, c
	add e
	mov c, a
	mov a, b
	adc d
	mov b, a
.L15:
	pop psw
	dcr a
	jnz .L13
	mov l, c
	mov h, b
	pop d
	dad d
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	lxi h, 4
	dad sp
	push h
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 10
	pop d
	xchg
	lxi b, 0
	mvi a, 16
.L16:
	push psw
	dad h
	mov a, c
	ral
	mov c, a
	mov a, b
	ral
	mov b, a
	mov a, c
	sub e
	mov c, a
	mov a, b
	sbb d
	mov b, a
	jc .L17
	inx h
	jmp .L18
.L17:
	mov a, c
	add e
	mov c, a
	mov a, b
	adc d
	mov b, a
.L18:
	pop psw
	dcr a
	jnz .L16
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	lxi h, 0
	dad sp
	push h
	lxi h, 0
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 1
	pop d
	dad d
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	jmp .L8
.L10:
.L7:
	lxi h, 2
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	; if
	mov a, h
	ora l
	jz .L19
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 0
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	pop d
	dad h
	dad d
	push h
	lxi h, 45
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	lxi h, 0
	dad sp
	push h
	lxi h, 0
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 1
	pop d
	dad d
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
.L19:
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 0
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	pop d
	dad h
	dad d
	push h
	lxi h, 0
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	lxi h, 6
	dad sp
	push h
	lxi h, 0
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	lxi h, 8
	dad sp
	push h
	lxi h, 0
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 1
	pop d
	xchg
	mov a, e
	sub l
	mov l, a
	mov a, d
	sbb h
	mov h, a
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	lxi h, 2
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	; if
	mov a, h
	ora l
	jz .L21
	lxi h, 8
	dad sp
	push h
	lxi h, 8
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 1
	pop d
	xchg
	mov a, e
	sub l
	mov l, a
	mov a, d
	sbb h
	mov h, a
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
.L21:
.L23:
	lxi h, 6
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 8
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	pop d
	xchg
	mov a, l
	sub e
	mov l, a
	mov a, h
	sbb d
	mov h, a
	jc .L26
	lxi h, 0
	jmp .L27
.L26:
	lxi h, 1
.L27:
	; while
	mov a, h
	ora l
	jz .L25
	lxi h, 4
	dad sp
	push h
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 6
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	pop d
	dad h
	dad d
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 6
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	pop d
	dad h
	dad d
	push h
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 8
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	pop d
	dad h
	dad d
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 8
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	pop d
	dad h
	dad d
	push h
	lxi h, 4
	dad sp
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	lxi h, 6
	dad sp
	push h
	lxi h, 6
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 1
	pop d
	dad d
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	lxi h, 8
	dad sp
	push h
	lxi h, 8
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 1
	pop d
	xchg
	mov a, e
	sub l
	mov l, a
	mov a, d
	sbb h
	mov h, a
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	jmp .L23
.L25:
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	; return
	ret
	; function itoa epilogue
	ret
