; generated by hcbcomp-8080
; source: printf.b


section text
extern putchar
global _print_digit

section text
	; function _print_digit prologue
_print_digit:
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 10
	pop d
	xchg
	mov a, l
	sub e
	mov l, a
	mov a, h
	sbb d
	mov h, a
	jc .L0
	lxi h, 1
	jmp .L1
.L0:
	lxi h, 0
.L1:
	; if
	mov a, h
	ora l
	jz .L2
	lxi h, putchar
	; call putchar
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 10
	pop d
	xchg
	mov a, e
	sub l
	mov l, a
	mov a, d
	sbb h
	mov h, a
	push h
	lxi h, 97
	pop d
	dad d
	push h
	; call putchar(1 args)
	call putchar
	lxi h, 2
	dad sp
	sphl
	jmp .L3
.L2:
	lxi h, putchar
	; call putchar
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 48
	pop d
	dad d
	push h
	; call putchar(1 args)
	call putchar
	lxi h, 2
	dad sp
	sphl
.L3:
	; function _print_digit epilogue
	ret
global _print_u

section text
	; function _print_u prologue
_print_u:
	lxi h, 65532
	dad sp
	sphl
	lxi h, 2
	dad sp
	push h
	lxi h, 0
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 0
	pop d
	mov a, l
	sub e
	jnz .L4
	mov a, h
	sbb d
	jnz .L4
	lxi h, 1
	jmp .L5
.L4:
	lxi h, 0
.L5:
	; if
	mov a, h
	ora l
	jz .L6
	lxi h, 0
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 0
	pop d
	dad h
	dad d
	push h
	lxi h, 48
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	lxi h, 2
	dad sp
	push h
	lxi h, 1
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	jmp .L7
.L6:
.L8:
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 0
	pop d
	xchg
	mov a, l
	sub e
	mov l, a
	mov a, h
	sbb d
	mov h, a
	jc .L11
	jz .L11
	lxi h, 1
	jmp .L12
.L11:
	lxi h, 0
.L12:
	; while
	mov a, h
	ora l
	jz .L10
	lxi h, 0
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 2
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	pop d
	dad h
	dad d
	push h
	lxi h, 48
	push h
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 10
	pop d
	xchg
	lxi b, 0
	mvi a, 16
.L13:
	push psw
	dad h
	mov a, c
	ral
	mov c, a
	mov a, b
	ral
	mov b, a
	mov a, c
	sub e
	mov c, a
	mov a, b
	sbb d
	mov b, a
	jc .L14
	inx h
	jmp .L15
.L14:
	mov a, c
	add e
	mov c, a
	mov a, b
	adc d
	mov b, a
.L15:
	pop psw
	dcr a
	jnz .L13
	mov l, c
	mov h, b
	pop d
	dad d
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	lxi h, 4
	dad sp
	push h
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 10
	pop d
	xchg
	lxi b, 0
	mvi a, 16
.L16:
	push psw
	dad h
	mov a, c
	ral
	mov c, a
	mov a, b
	ral
	mov b, a
	mov a, c
	sub e
	mov c, a
	mov a, b
	sbb d
	mov b, a
	jc .L17
	inx h
	jmp .L18
.L17:
	mov a, c
	add e
	mov c, a
	mov a, b
	adc d
	mov b, a
.L18:
	pop psw
	dcr a
	jnz .L16
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	lxi h, 2
	dad sp
	push h
	lxi h, 2
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 1
	pop d
	dad d
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	jmp .L8
.L10:
.L7:
.L19:
	lxi h, 2
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 0
	pop d
	xchg
	mov a, l
	sub e
	mov l, a
	mov a, h
	sbb d
	mov h, a
	jc .L22
	jz .L22
	lxi h, 1
	jmp .L23
.L22:
	lxi h, 0
.L23:
	; while
	mov a, h
	ora l
	jz .L21
	lxi h, 2
	dad sp
	push h
	lxi h, 2
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 1
	pop d
	xchg
	mov a, e
	sub l
	mov l, a
	mov a, d
	sbb h
	mov h, a
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	lxi h, putchar
	; call putchar
	lxi h, 0
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 2
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	pop d
	dad h
	dad d
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	; call putchar(1 args)
	call putchar
	lxi h, 2
	dad sp
	sphl
	jmp .L19
.L21:
	; function _print_u epilogue
	ret
global _print_s

section text
	; function _print_s prologue
_print_s:
	lxi h, 65534
	dad sp
	sphl
	lxi h, 0
	dad sp
	push h
	lxi h, 0
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
.L24:
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 0
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	pop d
	dad h
	dad d
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 0
	pop d
	mov a, l
	sub e
	jnz .L27
	mov a, h
	sbb d
	jz .L28
.L27:
	lxi h, 1
	jmp .L28
.L28:
	lxi h, 0
	; while
	mov a, h
	ora l
	jz .L26
	lxi h, putchar
	; call putchar
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 0
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	pop d
	dad h
	dad d
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	; call putchar(1 args)
	call putchar
	lxi h, 2
	dad sp
	sphl
	lxi h, 0
	dad sp
	push h
	lxi h, 0
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 1
	pop d
	dad d
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	jmp .L24
.L26:
	; function _print_s epilogue
	ret
global _print_x

section text
	; function _print_x prologue
_print_x:
	lxi h, 65530
	dad sp
	sphl
	lxi h, 0
	dad sp
	push h
	lxi h, 0
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
.L29:
	lxi h, 0
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 4
	pop d
	xchg
	mov a, l
	sub e
	mov l, a
	mov a, h
	sbb d
	mov h, a
	jc .L32
	lxi h, 0
	jmp .L33
.L32:
	lxi h, 1
.L33:
	; while
	mov a, h
	ora l
	jz .L31
	lxi h, 2
	dad sp
	push h
	lxi h, 12
	push h
	lxi h, 0
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 4
	pop d
	xchg
	push h
	pop b
	lxi h, 0
	mvi a, 16
.L34:
	push psw
	mov a, b
	rar
	mov b, a
	mov a, c
	rar
	mov c, a
	jnc .L35
	dad d
.L35:
	xchg
	dad h
	xchg
	pop psw
	dcr a
	jnz .L34
	pop d
	xchg
	mov a, e
	sub l
	mov l, a
	mov a, d
	sbb h
	mov h, a
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	lxi h, 4
	dad sp
	push h
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 2
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	pop d
	xchg
	mov a, e
	ora a
	jz .L36
.L37:
	push psw
	mov a, h
	rar
	mov h, a
	mov a, l
	rar
	mov l, a
	pop psw
	dcr a
	jnz .L37
.L36:
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	lxi h, 4
	dad sp
	push h
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 15
	pop d
	mov a, l
	ana e
	mov l, a
	mov a, h
	ana d
	mov h, a
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
extern _print_digit
	lxi h, _print_digit
	; call _print_digit
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	; call _print_digit(1 args)
	call _print_digit
	lxi h, 2
	dad sp
	sphl
	lxi h, 0
	dad sp
	push h
	lxi h, 0
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 1
	pop d
	dad d
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	jmp .L29
.L31:
	; function _print_x epilogue
	ret
global printf

section text
	; function printf prologue
printf:
	lxi h, 65530
	dad sp
	sphl
	lxi h, 0
	dad sp
	push h
	lxi h, 0
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	lxi h, 4
	dad sp
	push h
	lxi h, 4
	dad sp
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
.L38:
	lxi h, 1
	; while
	mov a, h
	ora l
	jz .L40
	lxi h, 2
	dad sp
	push h
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 0
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	pop d
	dad h
	dad d
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	lxi h, 2
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 0
	pop d
	mov a, l
	sub e
	jnz .L41
	mov a, h
	sbb d
	jnz .L41
	lxi h, 1
	jmp .L42
.L41:
	lxi h, 0
.L42:
	; if
	mov a, h
	ora l
	jz .L43
	; return
	ret
.L43:
	lxi h, 2
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 37
	pop d
	mov a, l
	sub e
	jnz .L45
	mov a, h
	sbb d
	jnz .L45
	lxi h, 1
	jmp .L46
.L45:
	lxi h, 0
.L46:
	; if
	mov a, h
	ora l
	jz .L47
	lxi h, 0
	dad sp
	push h
	lxi h, 0
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 1
	pop d
	dad d
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	lxi h, 2
	dad sp
	push h
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 0
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	pop d
	dad h
	dad d
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	lxi h, 2
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 100
	pop d
	mov a, l
	sub e
	jnz .L49
	mov a, h
	sbb d
	jnz .L49
	lxi h, 1
	jmp .L50
.L49:
	lxi h, 0
.L50:
	; if
	mov a, h
	ora l
	jz .L51
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 32768
	pop d
	mov a, l
	ana e
	mov l, a
	mov a, h
	ana d
	mov h, a
	; if
	mov a, h
	ora l
	jz .L53
	lxi h, putchar
	; call putchar
	lxi h, 45
	push h
	; call putchar(1 args)
	call putchar
	lxi h, 2
	dad sp
	sphl
extern _print_u
	lxi h, _print_u
	; call _print_u
	lxi h, 0
	push h
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	pop d
	xchg
	mov a, e
	sub l
	mov l, a
	mov a, d
	sbb h
	mov h, a
	push h
	; call _print_u(1 args)
	call _print_u
	lxi h, 2
	dad sp
	sphl
	jmp .L54
.L53:
	lxi h, _print_u
	; call _print_u
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	; call _print_u(1 args)
	call _print_u
	lxi h, 2
	dad sp
	sphl
.L54:
	lxi h, 4
	dad sp
	push h
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 1
	pop d
	dad d
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	jmp .L52
.L51:
	lxi h, 2
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 117
	pop d
	mov a, l
	sub e
	jnz .L55
	mov a, h
	sbb d
	jnz .L55
	lxi h, 1
	jmp .L56
.L55:
	lxi h, 0
.L56:
	; if
	mov a, h
	ora l
	jz .L57
	lxi h, _print_u
	; call _print_u
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	; call _print_u(1 args)
	call _print_u
	lxi h, 2
	dad sp
	sphl
	lxi h, 4
	dad sp
	push h
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 1
	pop d
	dad d
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	jmp .L58
.L57:
	lxi h, 2
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 120
	pop d
	mov a, l
	sub e
	jnz .L59
	mov a, h
	sbb d
	jnz .L59
	lxi h, 1
	jmp .L60
.L59:
	lxi h, 0
.L60:
	; if
	mov a, h
	ora l
	jz .L61
extern _print_x
	lxi h, _print_x
	; call _print_x
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	; call _print_x(1 args)
	call _print_x
	lxi h, 2
	dad sp
	sphl
	lxi h, 4
	dad sp
	push h
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 1
	pop d
	dad d
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	jmp .L62
.L61:
	lxi h, 2
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 115
	pop d
	mov a, l
	sub e
	jnz .L63
	mov a, h
	sbb d
	jnz .L63
	lxi h, 1
	jmp .L64
.L63:
	lxi h, 0
.L64:
	; if
	mov a, h
	ora l
	jz .L65
extern _print_s
	lxi h, _print_s
	; call _print_s
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	; call _print_s(1 args)
	call _print_s
	lxi h, 2
	dad sp
	sphl
	lxi h, 4
	dad sp
	push h
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 1
	pop d
	dad d
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	jmp .L66
.L65:
	lxi h, 2
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 99
	pop d
	mov a, l
	sub e
	jnz .L67
	mov a, h
	sbb d
	jnz .L67
	lxi h, 1
	jmp .L68
.L67:
	lxi h, 0
.L68:
	; if
	mov a, h
	ora l
	jz .L69
	lxi h, putchar
	; call putchar
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	; call putchar(1 args)
	call putchar
	lxi h, 2
	dad sp
	sphl
	lxi h, 4
	dad sp
	push h
	lxi h, 4
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 1
	pop d
	dad d
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	jmp .L70
.L69:
	lxi h, 2
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 37
	pop d
	mov a, l
	sub e
	jnz .L71
	mov a, h
	sbb d
	jnz .L71
	lxi h, 1
	jmp .L72
.L71:
	lxi h, 0
.L72:
	; if
	mov a, h
	ora l
	jz .L73
	lxi h, putchar
	; call putchar
	lxi h, 37
	push h
	; call putchar(1 args)
	call putchar
	lxi h, 2
	dad sp
	sphl
.L73:
.L70:
.L66:
.L62:
.L58:
.L52:
	lxi h, 0
	dad sp
	push h
	lxi h, 0
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 1
	pop d
	dad d
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
	jmp .L48
.L47:
	lxi h, putchar
	; call putchar
	lxi h, 2
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	; call putchar(1 args)
	call putchar
	lxi h, 2
	dad sp
	sphl
	lxi h, 0
	dad sp
	push h
	lxi h, 0
	dad sp
	mov a, m
	inx h
	mov h, m
	mov l, a
	push h
	lxi h, 1
	pop d
	dad d
	pop d
	xchg
	mov a, e
	mov m, a
	inx h
	mov a, d
	mov m, a
.L48:
	jmp .L38
.L40:
	; function printf epilogue
	ret
