#include "bcomp.h"

FILE *outfile = NULL;
FILE *devnull = NULL;
const char *target_cpu = "z80";

static void detect_cpu(const char *argv0)
{
    const char *p = strrchr(argv0, '-');
    if (p)
    {
        if (!strcmp(p, "-8086exe"))
            target_cpu = "8086mz";
        else if (!strcmp(p, "-8086"))
            target_cpu = "8086";
        else if (!strcmp(p, "-8080"))
            target_cpu = "8080";
        else if (!strcmp(p, "-8085"))
            target_cpu = "8085";
    }
}

static void help(void)
{
    printf("HC B Compiler for Retro Computing v%d.%d R%d\n", 2, 0, 0);
    printf("HC Software Development Kit for Retro Computing\n");
    printf("Copyright (c) 2025,2026 Humberto Costa dos Santos Junior\n\n");
    fprintf(stderr, "Usage: hcbcomp-{z80,8086,8080,8085} [options] <input.b>\n");
    fprintf(stderr, "Options:\n");
    fprintf(stderr, "  -o <file>          Output file (default: a.s)\n");
    fprintf(stderr, "  -I <dir>           Add include directory\n");
    fprintf(stderr, "  --help, -h         Show this help\n");
    exit(1);
}

int main(int argc, char **argv)
{
    char *input = NULL;
    char *output = NULL;

    detect_cpu(argv[0]);
    for (int i = 1; i < argc; i++)
    {
        if (!strcmp(argv[i], "-o"))
        {
            if (++i >= argc)
                help();
            output = argv[i];
        }
        else if (!strcmp(argv[i], "-I"))
        {
            if (++i >= argc)
                help();
            preproc_add_include_dir(argv[i]);
        }
        else if (!strcmp(argv[i], "--help") || !strcmp(argv[i], "-h"))
        {
            help();
        }
        else if (argv[i][0] == '-')
        {
            fprintf(stderr, "error: unknown option: %s\n", argv[i]);
            help();
        }
        else if (!input)
        {
            input = argv[i];
        }
        else
        {
            fprintf(stderr, "error: unexpected argument: %s\n", argv[i]);
            help();
        }
    }

    if (!input)
        help();
    if (!output)
        output = "a.s";

    FILE *fp = fopen(input, "r");
    if (!fp)
    {
        fprintf(stderr, "error: cannot open input file: %s\n", input);
        return 1;
    }
    fclose(fp);

    outfile = fopen(output, "w");
    if (!outfile)
    {
        fprintf(stderr, "error: cannot create output file: %s\n", output);
        return 1;
    }

    devnull = fopen("/dev/null", "w");
    if (!devnull)
    {
        fprintf(stderr, "error: cannot open /dev/null\n");
        return 1;
    }

    fprintf(outfile, "; generated by hcbcomp-%s\n", target_cpu);
    fprintf(outfile, "; source: %s\n\n", input);

    /* Run preprocessor to temp file */
    FILE *pp_out = tmpfile();
    if (!pp_out)
    {
        fprintf(stderr, "error: cannot create temp file\n");
        return 1;
    }
    preproc_run(input, pp_out, target_cpu);

    /* Lex from temp file */
    rewind(pp_out);
    /* Debug: dump preproc output */
    char _ppbuf[1024];
    rewind(pp_out);
    filename = input;
    lex_init(pp_out);

    next();
    compile_unit();

    fclose(outfile);
    fclose(devnull);
    fclose(pp_out);
    return 0;
}
