#include "bcomp.h"
#include "peep.h"

FILE *outfile = NULL;
FILE *devnull = NULL;
const char *target_cpu = "z80";

// [English] Detects the target CPU architecture from the executable name suffix
// (e.g. hcbcomp-z80, hcbcomp-8086, hcbcomp-8080, hcbcomp-8085, hcbcomp-8086exe)
// [Portuguese] Detecta a arquitetura de CPU alvo a partir do sufixo do nome do executável
// (ex.: hcbcomp-z80, hcbcomp-8086, hcbcomp-8080, hcbcomp-8085, hcbcomp-8086exe)
static void detect_cpu(const char *argv0)
{
    const char *p = strrchr(argv0, '-');
    if (p)
    {
        if (!strcmp(p, "-8086exe"))
            target_cpu = "8086mz";
        else if (!strcmp(p, "-8086"))
            target_cpu = "8086";
        else if (!strcmp(p, "-8080"))
            target_cpu = "8080";
        else if (!strcmp(p, "-8085"))
            target_cpu = "8085";
    }
}

// [English] Displays the help message with usage instructions and available options
// [Portuguese] Exibe a mensagem de ajuda com instruções de uso e opções disponíveis
static void help(void)
{
    printf("HC B Compiler for Retro Computing v%d.%d R%d\n", 2, 0, 0);
    printf("HC Software Development Kit for Retro Computing\n");
    printf("Copyright (c) 2025,2026 Humberto Costa dos Santos Junior\n\n");
    fprintf(stderr, "Usage: hcbcomp-{z80,8086,8080,8085} [options] <input.b>\n");
    fprintf(stderr, "Options:\n");
    fprintf(stderr, "  -o <file>          Output file (default: a.s)\n");
    fprintf(stderr, "  -I <dir>           Add include directory\n");
    fprintf(stderr, "  --help, -h         Show this help\n");
    exit(1);
}

// [English] Main entry point: parses command-line arguments, runs the preprocessor,
// lexer, parser, and peephole optimizer, then writes the output assembly file
// [Portuguese] Ponto de entrada principal: analisa argumentos da linha de comando,
// executa o pré-processador, analisador léxico, analisador sintático e otimizador
// peephole, então escreve o arquivo assembly de saída
int main(int argc, char **argv)
{
    char *input = NULL;
    char *output = NULL;

    detect_cpu(argv[0]);

    // Parse command-line arguments / Analisa argumentos da linha de comando
    for (int i = 1; i < argc; i++)
    {
        if (!strcmp(argv[i], "-o"))
        {
            if (++i >= argc)
                help();
            output = argv[i];
        }
        else if (!strcmp(argv[i], "-I"))
        {
            if (++i >= argc)
                help();
            preproc_add_include_dir(argv[i]);
        }
        else if (!strcmp(argv[i], "--help") || !strcmp(argv[i], "-h"))
        {
            help();
        }
        else if (argv[i][0] == '-')
        {
            fprintf(stderr, "error: unknown option: %s\n", argv[i]);
            help();
        }
        else if (!input)
        {
            input = argv[i];
        }
        else
        {
            fprintf(stderr, "error: unexpected argument: %s\n", argv[i]);
            help();
        }
    }

    if (!input)
        help();
    if (!output)
        output = "a.s";

    // Open input file / Abre arquivo de entrada
    FILE *fp = fopen(input, "r");
    if (!fp)
    {
        fprintf(stderr, "error: cannot open input file: %s\n", input);
        return 1;
    }
    fclose(fp);

    // Create temp file for output / Cria arquivo temporário para saída
    outfile = tmpfile();
    if (!outfile)
    {
        fprintf(stderr, "error: cannot create temp file\n");
        return 1;
    }

    devnull = fopen("/dev/null", "w");
    if (!devnull)
    {
        fprintf(stderr, "error: cannot open /dev/null\n");
        return 1;
    }

    // Run preprocessor to temp file / Executa pré-processador para arquivo temporário
    FILE *pp_out = tmpfile();
    if (!pp_out)
    {
        fprintf(stderr, "error: cannot create temp file\n");
        return 1;
    }
    preproc_run(input, pp_out, target_cpu);

    // Lex from temp file / Analisa léxicamente a partir do arquivo temporário
    rewind(pp_out);
    filename = input;
    lex_init(pp_out);

    next();
    compile_unit();

    // Peephole optimization / Otimização peephole
    rewind(outfile);
    FILE *real_out = fopen(output, "w");
    if (!real_out)
    {
        fprintf(stderr, "error: cannot create output file: %s\n", output);
        return 1;
    }
    fprintf(real_out, "; generated by hcbcomp-%s\n", target_cpu);
    fprintf(real_out, "; source: %s\n\n", input);

    peep_apply(outfile, real_out, target_cpu);

    fclose(outfile);
    fclose(real_out);
    fclose(devnull);
    fclose(pp_out);
    return 0;
}
