// [English] DO NOT MODIFY; This file was automatically generated by Make.
// [Portuguese] NAO MODIFICAR; Este arquivo foi gerado automaticamente pelo Make.
#pragma once
// [English] DO NOT MODIFY; This file was automatically generated by Make.
// [Portuguese] NAO MODIFICAR; Este arquivo foi gerado automaticamente pelo Make.

// [English] SDK major version number
// [Portuguese] Numero da versao principal do SDK
#define VERSION 2

// [English] DO NOT MODIFY; This file was automatically generated by Make.
// [Portuguese] NAO MODIFICAR; Este arquivo foi gerado automaticamente pelo Make.

// [English] SDK minor version number
// [Portuguese] Numero da versao secundaria do SDK
#define SUBVERSION 1

// [English] DO NOT MODIFY; This file was automatically generated by Make.
// [Portuguese] NAO MODIFICAR; Este arquivo foi gerado automaticamente pelo Make.

// [English] SDK revision number
// [Portuguese] Numero de revisao do SDK
#define REVISION 2
