; generated by hcbcomp-z80
; source: abs.b


section text
global abs

section text
	; function abs prologue
abs:
	push ix
	ld ix, 0
	add ix, sp
	ld hl, 4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 0
	pop de
	or a
	sbc hl, de
	ld hl, 0
	jr nc, .L0
	inc hl
.L0:
	; if
	ld a, h
	or l
	jp z, .L1
	ld hl, 0
	push hl
	ld hl, 4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	pop de
	ex de, hl
	or a
	sbc hl, de
	; return
	ld sp, ix
	pop ix
	ret
.L1:
	ld hl, 4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	; return
	ld sp, ix
	pop ix
	ret
	; function abs epilogue
	ld sp, ix
	pop ix
	ret
