; generated by hcbcomp-z80
; source: atoi.b


section text
global atoi

section text
	; function atoi prologue
atoi:
	push ix
	ld ix, 0
	add ix, sp
	ld hl, -6
	add hl, sp
	ld sp, hl
	ld hl, -2
	add hl, ix
	push hl
	ld hl, 0
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	ld hl, -6
	add hl, ix
	push hl
	ld hl, 1
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	ld hl, 4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	pop de
	add hl, hl
	add hl, de
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 45
	pop de
	or a
	sbc hl, de
	ld hl, 0
	jr nz, .L0
	inc hl
.L0:
	; if
	ld a, h
	or l
	jp z, .L1
	ld hl, -6
	add hl, ix
	push hl
	ld hl, 0
	push hl
	ld hl, 1
	pop de
	ex de, hl
	or a
	sbc hl, de
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	ld hl, -2
	add hl, ix
	push hl
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 1
	pop de
	add hl, de
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	jp .L2
.L1:
	ld hl, 4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	pop de
	add hl, hl
	add hl, de
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 43
	pop de
	or a
	sbc hl, de
	ld hl, 0
	jr nz, .L3
	inc hl
.L3:
	; if
	ld a, h
	or l
	jp z, .L4
	ld hl, -2
	add hl, ix
	push hl
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 1
	pop de
	add hl, de
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
.L4:
.L2:
	ld hl, -4
	add hl, ix
	push hl
	ld hl, 0
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
.L6:
	ld hl, 4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	pop de
	add hl, hl
	add hl, de
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 48
	pop de
	or a
	sbc hl, de
	ld hl, 0
	jr c, .L9
	inc hl
.L9:
	; && short-circuit
	ld a, h
	or l
	jp z, .L10
	ld hl, 4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	pop de
	add hl, hl
	add hl, de
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 57
	pop de
	or a
	sbc hl, de
	ld hl, 0
	jr c, .L12
	jr z, .L12
	inc hl
.L12:
	ld a, h
	or l
	jp z, .L10
	ld hl, 1
	jp .L11
.L10:
	ld hl, 0
.L11:
	; while
	ld a, h
	or l
	jp z, .L8
	ld hl, -4
	add hl, ix
	push hl
	ld hl, -4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 10
	pop de
	push de
	push hl
	pop bc
	ld hl, 0
	ld a, 16
.L13:
	srl b
	rr c
	jr nc, .L14
	add hl, de
.L14:
	sla e
	rl d
	dec a
	jr nz, .L13
	pop de
	push hl
	ld hl, 4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	pop de
	add hl, hl
	add hl, de
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 48
	pop de
	ex de, hl
	or a
	sbc hl, de
	pop de
	add hl, de
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	ld hl, -2
	add hl, ix
	push hl
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 1
	pop de
	add hl, de
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	jp .L6
.L8:
	ld hl, -4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, -6
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	pop de
	push de
	push hl
	pop bc
	ld hl, 0
	ld a, 16
.L15:
	srl b
	rr c
	jr nc, .L16
	add hl, de
.L16:
	sla e
	rl d
	dec a
	jr nz, .L15
	pop de
	; return
	ld sp, ix
	pop ix
	ret
	; function atoi epilogue
	ld sp, ix
	pop ix
	ret
