; generated by hcbcomp-z80
; source: z80/cpm_byte.b


section text
extern ft
global setb

section text
	; function setb prologue
setb:
	push ix
	ld ix, 0
	add ix, sp
	ld hl, -6
	add hl, sp
	ld sp, hl
	ld hl, -2
	add hl, ix
	push hl
	ld hl, 4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 2
	pop de
	ex de, hl
	ld a, 16
	ld bc, 0
.L0:
	push af
	add hl, hl
	rl c
	rl b
	ld a, c
	sub e
	ld c, a
	ld a, b
	sbc a, d
	ld b, a
	jr c, .L1
	inc hl
	jr .L2
.L1:
	ld a, c
	add a, e
	ld c, a
	ld a, b
	adc a, d
	ld b, a
.L2:
	pop af
	dec a
	jr nz, .L0
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	ld hl, -4
	add hl, ix
	push hl
	ld hl, 4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 2
	pop de
	ex de, hl
	ld a, 16
	ld bc, 0
.L3:
	push af
	add hl, hl
	rl c
	rl b
	ld a, c
	sub e
	ld c, a
	ld a, b
	sbc a, d
	ld b, a
	jr c, .L4
	inc hl
	jr .L5
.L4:
	ld a, c
	add a, e
	ld c, a
	ld a, b
	adc a, d
	ld b, a
.L5:
	pop af
	dec a
	jr nz, .L3
	push bc
	pop hl
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	ld hl, -6
	add hl, ix
	push hl
	ld hl, 4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	pop de
	add hl, de
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	ld hl, -4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 0
	pop de
	or a
	sbc hl, de
	ld hl, 0
	jr nz, .L6
	inc hl
.L6:
	; if
	ld a, h
	or l
	jp z, .L7
	ld hl, 4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	pop de
	add hl, de
	push hl
	ld hl, -6
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 65280
	pop de
	ld a, e
	and l
	ld l, a
	ld a, d
	and h
	ld h, a
	push hl
	ld hl, 4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	pop de
	ld a, e
	or l
	ld l, a
	ld a, d
	or h
	ld h, a
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	jp .L8
.L7:
	ld hl, 4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	pop de
	add hl, de
	push hl
	ld hl, -6
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 255
	pop de
	ld a, e
	and l
	ld l, a
	ld a, d
	and h
	ld h, a
	push hl
	ld hl, 4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 8
	pop de
	ex de, hl
	ld a, e
	or a
	jr z, .L9
.L10:
	add hl, hl
	dec a
	jr nz, .L10
.L9:
	pop de
	ld a, e
	or l
	ld l, a
	ld a, d
	or h
	ld h, a
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
.L8:
	; function setb epilogue
	ld sp, ix
	pop ix
	ret
global getb

section text
	; function getb prologue
getb:
	push ix
	ld ix, 0
	add ix, sp
	ld hl, -6
	add hl, sp
	ld sp, hl
	ld hl, -2
	add hl, ix
	push hl
	ld hl, 4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 2
	pop de
	ex de, hl
	ld a, 16
	ld bc, 0
.L11:
	push af
	add hl, hl
	rl c
	rl b
	ld a, c
	sub e
	ld c, a
	ld a, b
	sbc a, d
	ld b, a
	jr c, .L12
	inc hl
	jr .L13
.L12:
	ld a, c
	add a, e
	ld c, a
	ld a, b
	adc a, d
	ld b, a
.L13:
	pop af
	dec a
	jr nz, .L11
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	ld hl, -4
	add hl, ix
	push hl
	ld hl, 4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 2
	pop de
	ex de, hl
	ld a, 16
	ld bc, 0
.L14:
	push af
	add hl, hl
	rl c
	rl b
	ld a, c
	sub e
	ld c, a
	ld a, b
	sbc a, d
	ld b, a
	jr c, .L15
	inc hl
	jr .L16
.L15:
	ld a, c
	add a, e
	ld c, a
	ld a, b
	adc a, d
	ld b, a
.L16:
	pop af
	dec a
	jr nz, .L14
	push bc
	pop hl
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	ld hl, -6
	add hl, ix
	push hl
	ld hl, 4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	pop de
	add hl, de
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	ld hl, -4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 0
	pop de
	or a
	sbc hl, de
	ld hl, 0
	jr nz, .L17
	inc hl
.L17:
	; if
	ld a, h
	or l
	jp z, .L18
	ld hl, -6
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 255
	pop de
	ld a, e
	and l
	ld l, a
	ld a, d
	and h
	ld h, a
	; return
	ld sp, ix
	pop ix
	ret
	jp .L19
.L18:
	ld hl, -6
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 8
	pop de
	ex de, hl
	ld a, e
	or a
	jr z, .L20
.L21:
	srl h
	rr l
	dec a
	jr nz, .L21
.L20:
	push hl
	ld hl, 255
	pop de
	ld a, e
	and l
	ld l, a
	ld a, d
	and h
	ld h, a
	; return
	ld sp, ix
	pop ix
	ret
.L19:
	; function getb epilogue
	ld sp, ix
	pop ix
	ret
