; generated by hcbcomp-z80
; source: z80/cpm_str.b


section text
global strc

section text
	; function strc prologue
strc:
	push ix
	ld ix, 0
	add ix, sp
	ld hl, -4
	add hl, sp
	ld sp, hl
	ld hl, -2
	add hl, ix
	push hl
	ld hl, 4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 2
	pop de
	ex de, hl
	ld a, 16
	ld bc, 0
.L0:
	push af
	add hl, hl
	rl c
	rl b
	ld a, c
	sub e
	ld c, a
	ld a, b
	sbc a, d
	ld b, a
	jr c, .L1
	inc hl
	jr .L2
.L1:
	ld a, c
	add a, e
	ld c, a
	ld a, b
	adc a, d
	ld b, a
.L2:
	pop af
	dec a
	jr nz, .L0
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	ld hl, -4
	add hl, ix
	push hl
	ld hl, 4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 2
	pop de
	ex de, hl
	ld a, 16
	ld bc, 0
.L3:
	push af
	add hl, hl
	rl c
	rl b
	ld a, c
	sub e
	ld c, a
	ld a, b
	sbc a, d
	ld b, a
	jr c, .L4
	inc hl
	jr .L5
.L4:
	ld a, c
	add a, e
	ld c, a
	ld a, b
	adc a, d
	ld b, a
.L5:
	pop af
	dec a
	jr nz, .L3
	push bc
	pop hl
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	ld hl, -4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 0
	pop de
	or a
	sbc hl, de
	ld hl, 0
	jr nz, .L6
	inc hl
.L6:
	; if
	ld a, h
	or l
	jp z, .L7
	ld hl, 4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	pop de
	add hl, hl
	add hl, de
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 255
	pop de
	ld a, e
	and l
	ld l, a
	ld a, d
	and h
	ld h, a
	; return
	ld sp, ix
	pop ix
	ret
	jp .L8
.L7:
	ld hl, 4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	pop de
	add hl, hl
	add hl, de
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 8
	pop de
	ex de, hl
	ld a, e
	or a
	jr z, .L9
.L10:
	srl h
	rr l
	dec a
	jr nz, .L10
.L9:
	push hl
	ld hl, 255
	pop de
	ld a, e
	and l
	ld l, a
	ld a, d
	and h
	ld h, a
	; return
	ld sp, ix
	pop ix
	ret
.L8:
	; function strc epilogue
	ld sp, ix
	pop ix
	ret
global toup

section text
	; function toup prologue
toup:
	push ix
	ld ix, 0
	add ix, sp
	ld hl, 4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 97
	pop de
	or a
	sbc hl, de
	ld hl, 0
	jr c, .L11
	inc hl
.L11:
	; && short-circuit
	ld a, h
	or l
	jp z, .L12
	ld hl, 4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 122
	pop de
	or a
	sbc hl, de
	ld hl, 0
	jr c, .L14
	jr z, .L14
	inc hl
.L14:
	ld a, h
	or l
	jp z, .L12
	ld hl, 1
	jp .L13
.L12:
	ld hl, 0
.L13:
	; if
	ld a, h
	or l
	jp z, .L15
	ld hl, 4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 32
	pop de
	ex de, hl
	or a
	sbc hl, de
	; return
	ld sp, ix
	pop ix
	ret
.L15:
	ld hl, 4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	; return
	ld sp, ix
	pop ix
	ret
	; function toup epilogue
	ld sp, ix
	pop ix
	ret
