; generated by hcbcomp-z80
; source: z80/cpm_slot.b


section text
extern ft
global find_slot

section text
	; function find_slot prologue
find_slot:
	push ix
	ld ix, 0
	add ix, sp
	ld hl, -2
	add hl, sp
	ld sp, hl
	ld hl, -2
	add hl, ix
	push hl
	ld hl, 0
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
.L0:
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 5
	pop de
	or a
	sbc hl, de
	ld hl, 0
	jr nc, .L3
	inc hl
.L3:
	; while
	ld a, h
	or l
	jp z, .L2
	ld hl, ft
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 24
	pop de
	push de
	push hl
	pop bc
	ld hl, 0
	ld a, 16
.L4:
	srl b
	rr c
	jr nc, .L5
	add hl, de
.L5:
	sla e
	rl d
	dec a
	jr nz, .L4
	pop de
	push hl
	ld hl, 23
	pop de
	add hl, de
	pop de
	add hl, hl
	add hl, de
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 0
	pop de
	or a
	sbc hl, de
	ld hl, 0
	jr nz, .L6
	inc hl
.L6:
	; if
	ld a, h
	or l
	jp z, .L7
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	; return
	ld sp, ix
	pop ix
	ret
.L7:
	ld hl, -2
	add hl, ix
	push hl
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 1
	pop de
	add hl, de
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	jp .L0
.L2:
	ld hl, 1
	ex de, hl
	ld hl, 0
	or a
	sbc hl, de
	; return
	ld sp, ix
	pop ix
	ret
	; function find_slot epilogue
	ld sp, ix
	pop ix
	ret
