; generated by hcbcomp-z80
; source: z80/cpm_name.b


section text
extern ft
extern setb
extern getb
extern strc
extern toup
global name2fcb

section text
	; function name2fcb prologue
name2fcb:
	push ix
	ld ix, 0
	add ix, sp
	ld hl, -8
	add hl, sp
	ld sp, hl
	ld hl, -2
	add hl, ix
	push hl
	ld hl, 4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 24
	pop de
	push de
	push hl
	pop bc
	ld hl, 0
	ld a, 16
.L0:
	srl b
	rr c
	jr nc, .L1
	add hl, de
.L1:
	sla e
	rl d
	dec a
	jr nz, .L0
	pop de
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	ld hl, -4
	add hl, ix
	push hl
	ld hl, 0
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
.L2:
	ld hl, -4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 18
	pop de
	or a
	sbc hl, de
	ld hl, 0
	jr nc, .L5
	inc hl
.L5:
	; while
	ld a, h
	or l
	jp z, .L4
	ld hl, ft
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, -4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	pop de
	add hl, de
	pop de
	add hl, hl
	add hl, de
	push hl
	ld hl, 8224
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	ld hl, -4
	add hl, ix
	push hl
	ld hl, -4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 1
	pop de
	add hl, de
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	jp .L2
.L4:
	ld hl, ft
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	pop de
	add hl, hl
	add hl, de
	push hl
	ld hl, 0
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	ld hl, -4
	add hl, ix
	push hl
	ld hl, 0
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	ld hl, -8
	add hl, ix
	push hl
	ld hl, 1
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
.L6:
	ld hl, 1
	; while
	ld a, h
	or l
	jp z, .L8
	ld hl, -6
	add hl, ix
	push hl
	ld hl, strc
	; call strc
	ld hl, 4
	add hl, ix
	ld hl, -4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	; call strc(2 args)
	call strc
	ld hl, 4
	add hl, sp
	ld sp, hl
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	ld hl, -6
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 0
	pop de
	or a
	sbc hl, de
	ld hl, 0
	jr nz, .L9
	inc hl
.L9:
	; if
	ld a, h
	or l
	jp z, .L10
	; return
	ld sp, ix
	pop ix
	ret
.L10:
	ld hl, -4
	add hl, ix
	push hl
	ld hl, -4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 1
	pop de
	add hl, de
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	ld hl, -6
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 58
	pop de
	or a
	sbc hl, de
	ld hl, 0
	jr nz, .L12
	inc hl
.L12:
	; if
	ld a, h
	or l
	jp z, .L13
	ld hl, -4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 1
	pop de
	or a
	sbc hl, de
	ld hl, 0
	jr z, .L15
	jr c, .L15
	inc hl
.L15:
	; if
	ld a, h
	or l
	jp z, .L16
	ld hl, -6
	add hl, ix
	push hl
	ld hl, strc
	; call strc
	ld hl, 4
	add hl, ix
	ld hl, -4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 2
	pop de
	ex de, hl
	or a
	sbc hl, de
	push hl
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	; call strc(2 args)
	call strc
	ld hl, 4
	add hl, sp
	ld sp, hl
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	ld hl, -6
	add hl, ix
	push hl
	ld hl, toup
	; call toup
	ld hl, -6
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	; call toup(1 args)
	call toup
	ld hl, 2
	add hl, sp
	ld sp, hl
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	ld hl, -6
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 65
	pop de
	or a
	sbc hl, de
	ld hl, 0
	jr c, .L18
	inc hl
.L18:
	; && short-circuit
	ld a, h
	or l
	jp z, .L19
	ld hl, -6
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 80
	pop de
	or a
	sbc hl, de
	ld hl, 0
	jr c, .L21
	jr z, .L21
	inc hl
.L21:
	ld a, h
	or l
	jp z, .L19
	ld hl, 1
	jp .L20
.L19:
	ld hl, 0
.L20:
	; if
	ld a, h
	or l
	jp z, .L22
	ld hl, setb
	; call setb
	ld hl, ft
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	pop de
	add hl, hl
	add hl, de
	ld hl, 0
	ld hl, -6
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 65
	pop de
	ex de, hl
	or a
	sbc hl, de
	push hl
	ld hl, 1
	pop de
	add hl, de
	push hl
	push hl
	push hl
	; call setb(3 args)
	call setb
	ld hl, 6
	add hl, sp
	ld sp, hl
.L22:
.L16:
	ld hl, -8
	add hl, ix
	push hl
	ld hl, 1
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	jp .L14
.L13:
	ld hl, -6
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 46
	pop de
	or a
	sbc hl, de
	ld hl, 0
	jr nz, .L24
	inc hl
.L24:
	; if
	ld a, h
	or l
	jp z, .L25
	ld hl, -8
	add hl, ix
	push hl
	ld hl, 9
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	jp .L26
.L25:
	ld hl, -8
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 12
	pop de
	or a
	sbc hl, de
	ld hl, 0
	jr nc, .L27
	inc hl
.L27:
	; if
	ld a, h
	or l
	jp z, .L28
	ld hl, -6
	add hl, ix
	push hl
	ld hl, toup
	; call toup
	ld hl, -6
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	; call toup(1 args)
	call toup
	ld hl, 2
	add hl, sp
	ld sp, hl
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	ld hl, setb
	; call setb
	ld hl, ft
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	pop de
	add hl, hl
	add hl, de
	ld hl, -8
	add hl, ix
	ld hl, -6
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	push hl
	; call setb(3 args)
	call setb
	ld hl, 6
	add hl, sp
	ld sp, hl
	ld hl, -8
	add hl, ix
	push hl
	ld hl, -8
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 1
	pop de
	add hl, de
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
.L28:
.L26:
.L14:
	jp .L6
.L8:
	; function name2fcb epilogue
	ld sp, ix
	pop ix
	ret
