; generated by hcbcomp-z80
; source: z80/fdelete.b


section text
extern ft
extern name2fcb
extern find_slot
global fdelete

section text
	; function fdelete prologue
fdelete:
	push ix
	ld ix, 0
	add ix, sp
	ld hl, -4
	add hl, sp
	ld sp, hl
	ld hl, -2
	add hl, ix
	push hl
	ld hl, find_slot
	; call find_slot
	; call find_slot(0 args)
	call find_slot
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 0
	pop de
	or a
	sbc hl, de
	ld hl, 0
	jr nc, .L0
	inc hl
.L0:
	; if
	ld a, h
	or l
	jp z, .L1
	ld hl, 1
	ex de, hl
	ld hl, 0
	or a
	sbc hl, de
	; return
	ld sp, ix
	pop ix
	ret
.L1:
	ld hl, name2fcb
	; call name2fcb
	ld hl, -2
	add hl, ix
	ld hl, 4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	; call name2fcb(2 args)
	call name2fcb
	ld hl, 4
	add hl, sp
	ld sp, hl
	ld hl, -4
	add hl, ix
	push hl
extern bdos
	ld hl, bdos
	; call bdos
	ld hl, 19
	ld hl, ft
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 24
	pop de
	push de
	push hl
	pop bc
	ld hl, 0
	ld a, 16
.L3:
	srl b
	rr c
	jr nc, .L4
	add hl, de
.L4:
	sla e
	rl d
	dec a
	jr nz, .L3
	pop de
	pop de
	add hl, hl
	add hl, de
	push hl
	push hl
	; call bdos(2 args)
	call bdos
	ld hl, 4
	add hl, sp
	ld sp, hl
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	ld hl, ft
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 24
	pop de
	push de
	push hl
	pop bc
	ld hl, 0
	ld a, 16
.L5:
	srl b
	rr c
	jr nc, .L6
	add hl, de
.L6:
	sla e
	rl d
	dec a
	jr nz, .L5
	pop de
	push hl
	ld hl, 23
	pop de
	add hl, de
	pop de
	add hl, hl
	add hl, de
	push hl
	ld hl, 0
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	ld hl, -4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 0
	pop de
	or a
	sbc hl, de
	ld hl, 0
	jr nz, .L7
	inc hl
.L7:
	; if
	ld a, h
	or l
	jp z, .L8
	ld hl, 0
	; return
	ld sp, ix
	pop ix
	ret
.L8:
	ld hl, 1
	ex de, hl
	ld hl, 0
	or a
	sbc hl, de
	; return
	ld sp, ix
	pop ix
	ret
	; function fdelete epilogue
	ld sp, ix
	pop ix
	ret
