; generated by hcbcomp-z80
; source: z80/feof.b


section text
extern ft
global feof

section text
	; function feof prologue
feof:
	push ix
	ld ix, 0
	add ix, sp
	ld hl, 4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 0
	pop de
	or a
	sbc hl, de
	ld hl, 0
	jr nc, .L0
	inc hl
.L0:
	; || short-circuit
	ld a, h
	or l
	jp nz, .L1
	ld hl, 4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 5
	pop de
	or a
	sbc hl, de
	ld hl, 0
	jr c, .L3
	inc hl
.L3:
	ld a, h
	or l
	jp nz, .L1
	ld hl, 0
	jp .L2
.L1:
	ld hl, 1
.L2:
	; if
	ld a, h
	or l
	jp z, .L4
	ld hl, 1
	ex de, hl
	ld hl, 0
	or a
	sbc hl, de
	; return
	ld sp, ix
	pop ix
	ret
.L4:
	ld hl, ft
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 24
	pop de
	push de
	push hl
	pop bc
	ld hl, 0
	ld a, 16
.L6:
	srl b
	rr c
	jr nc, .L7
	add hl, de
.L7:
	sla e
	rl d
	dec a
	jr nz, .L6
	pop de
	push hl
	ld hl, 21
	pop de
	add hl, de
	pop de
	add hl, hl
	add hl, de
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	; return
	ld sp, ix
	pop ix
	ret
	; function feof epilogue
	ld sp, ix
	pop ix
	ret
