; generated by hcbcomp-z80
; source: z80/frename.b


section text
extern ft
extern name2fcb
extern find_slot
extern strc
extern toup
extern setb
global frename

section text
	; function frename prologue
frename:
	push ix
	ld ix, 0
	add ix, sp
	ld hl, -8
	add hl, sp
	ld sp, hl
	ld hl, -2
	add hl, ix
	push hl
	ld hl, find_slot
	; call find_slot
	; call find_slot(0 args)
	call find_slot
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 0
	pop de
	or a
	sbc hl, de
	ld hl, 0
	jr nc, .L0
	inc hl
.L0:
	; if
	ld a, h
	or l
	jp z, .L1
	ld hl, 1
	ex de, hl
	ld hl, 0
	or a
	sbc hl, de
	; return
	ld sp, ix
	pop ix
	ret
.L1:
	ld hl, name2fcb
	; call name2fcb
	ld hl, -2
	add hl, ix
	ld hl, 4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	; call name2fcb(2 args)
	call name2fcb
	ld hl, 4
	add hl, sp
	ld sp, hl
	ld hl, -4
	add hl, ix
	push hl
	ld hl, 0
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
.L3:
	ld hl, -4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 12
	pop de
	or a
	sbc hl, de
	ld hl, 0
	jr nc, .L6
	inc hl
.L6:
	; while
	ld a, h
	or l
	jp z, .L5
	ld hl, -6
	add hl, ix
	push hl
	ld hl, strc
	; call strc
	ld hl, 4
	add hl, ix
	ld hl, -4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	; call strc(2 args)
	call strc
	ld hl, 4
	add hl, sp
	ld sp, hl
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	ld hl, -6
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 0
	pop de
	or a
	sbc hl, de
	ld hl, 0
	jr nz, .L7
	inc hl
.L7:
	; if
	ld a, h
	or l
	jp z, .L8
	ld hl, -6
	add hl, ix
	push hl
	ld hl, 32
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
.L8:
	ld hl, -6
	add hl, ix
	push hl
	ld hl, toup
	; call toup
	ld hl, -6
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	; call toup(1 args)
	call toup
	ld hl, 2
	add hl, sp
	ld sp, hl
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	ld hl, setb
	; call setb
	ld hl, ft
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 24
	pop de
	push de
	push hl
	pop bc
	ld hl, 0
	ld a, 16
.L10:
	srl b
	rr c
	jr nc, .L11
	add hl, de
.L11:
	sla e
	rl d
	dec a
	jr nz, .L10
	pop de
	pop de
	add hl, hl
	add hl, de
	ld hl, 17
	push hl
	ld hl, -4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	pop de
	add hl, de
	ld hl, -6
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	push hl
	push hl
	; call setb(3 args)
	call setb
	ld hl, 6
	add hl, sp
	ld sp, hl
	ld hl, -4
	add hl, ix
	push hl
	ld hl, -4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 1
	pop de
	add hl, de
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	jp .L3
.L5:
	ld hl, -8
	add hl, ix
	push hl
extern bdos
	ld hl, bdos
	; call bdos
	ld hl, 23
	ld hl, ft
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 24
	pop de
	push de
	push hl
	pop bc
	ld hl, 0
	ld a, 16
.L12:
	srl b
	rr c
	jr nc, .L13
	add hl, de
.L13:
	sla e
	rl d
	dec a
	jr nz, .L12
	pop de
	pop de
	add hl, hl
	add hl, de
	push hl
	push hl
	; call bdos(2 args)
	call bdos
	ld hl, 4
	add hl, sp
	ld sp, hl
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	ld hl, ft
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 24
	pop de
	push de
	push hl
	pop bc
	ld hl, 0
	ld a, 16
.L14:
	srl b
	rr c
	jr nc, .L15
	add hl, de
.L15:
	sla e
	rl d
	dec a
	jr nz, .L14
	pop de
	push hl
	ld hl, 23
	pop de
	add hl, de
	pop de
	add hl, hl
	add hl, de
	push hl
	ld hl, 0
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	ld hl, -8
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 0
	pop de
	or a
	sbc hl, de
	ld hl, 0
	jr nz, .L16
	inc hl
.L16:
	; if
	ld a, h
	or l
	jp z, .L17
	ld hl, 0
	; return
	ld sp, ix
	pop ix
	ret
.L17:
	ld hl, 1
	ex de, hl
	ld hl, 0
	or a
	sbc hl, de
	; return
	ld sp, ix
	pop ix
	ret
	; function frename epilogue
	ld sp, ix
	pop ix
	ret
