; generated by hcbcomp-z80
; source: z80/fseek.b


section text
extern ft
global fseek

section text
	; function fseek prologue
fseek:
	push ix
	ld ix, 0
	add ix, sp
	ld hl, -4
	add hl, sp
	ld sp, hl
	ld hl, 4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 0
	pop de
	or a
	sbc hl, de
	ld hl, 0
	jr nc, .L0
	inc hl
.L0:
	; || short-circuit
	ld a, h
	or l
	jp nz, .L1
	ld hl, 4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 5
	pop de
	or a
	sbc hl, de
	ld hl, 0
	jr c, .L3
	inc hl
.L3:
	ld a, h
	or l
	jp nz, .L1
	ld hl, 0
	jp .L2
.L1:
	ld hl, 1
.L2:
	; if
	ld a, h
	or l
	jp z, .L4
	ld hl, 1
	ex de, hl
	ld hl, 0
	or a
	sbc hl, de
	; return
	ld sp, ix
	pop ix
	ret
.L4:
	ld hl, -2
	add hl, ix
	push hl
	ld hl, 4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 24
	pop de
	push de
	push hl
	pop bc
	ld hl, 0
	ld a, 16
.L6:
	srl b
	rr c
	jr nc, .L7
	add hl, de
.L7:
	sla e
	rl d
	dec a
	jr nz, .L6
	pop de
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	ld hl, ft
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 23
	pop de
	add hl, de
	pop de
	add hl, hl
	add hl, de
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 0
	pop de
	or a
	sbc hl, de
	ld hl, 0
	jr nz, .L8
	inc hl
.L8:
	; if
	ld a, h
	or l
	jp z, .L9
	ld hl, 1
	ex de, hl
	ld hl, 0
	or a
	sbc hl, de
	; return
	ld sp, ix
	pop ix
	ret
.L9:
	ld hl, 4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 0
	pop de
	or a
	sbc hl, de
	ld hl, 0
	jr nz, .L11
	inc hl
.L11:
	; if
	ld a, h
	or l
	jp z, .L12
	ld hl, ft
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 19
	pop de
	add hl, de
	pop de
	add hl, hl
	add hl, de
	push hl
	ld hl, 4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 128
	pop de
	ex de, hl
	ld a, 16
	ld bc, 0
.L14:
	push af
	add hl, hl
	rl c
	rl b
	ld a, c
	sub e
	ld c, a
	ld a, b
	sbc a, d
	ld b, a
	jr c, .L15
	inc hl
	jr .L16
.L15:
	ld a, c
	add a, e
	ld c, a
	ld a, b
	adc a, d
	ld b, a
.L16:
	pop af
	dec a
	jr nz, .L14
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	ld hl, ft
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 18
	pop de
	add hl, de
	pop de
	add hl, hl
	add hl, de
	push hl
	ld hl, 4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 128
	pop de
	ex de, hl
	ld a, 16
	ld bc, 0
.L17:
	push af
	add hl, hl
	rl c
	rl b
	ld a, c
	sub e
	ld c, a
	ld a, b
	sbc a, d
	ld b, a
	jr c, .L18
	inc hl
	jr .L19
.L18:
	ld a, c
	add a, e
	ld c, a
	ld a, b
	adc a, d
	ld b, a
.L19:
	pop af
	dec a
	jr nz, .L17
	push bc
	pop hl
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	ld hl, ft
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 20
	pop de
	add hl, de
	pop de
	add hl, hl
	add hl, de
	push hl
	ld hl, 0
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	ld hl, ft
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 21
	pop de
	add hl, de
	pop de
	add hl, hl
	add hl, de
	push hl
	ld hl, 0
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	ld hl, 0
	; return
	ld sp, ix
	pop ix
	ret
.L12:
	ld hl, 4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 2
	pop de
	or a
	sbc hl, de
	ld hl, 0
	jr nz, .L20
	inc hl
.L20:
	; if
	ld a, h
	or l
	jp z, .L21
	ld hl, -4
	add hl, ix
	push hl
extern bdos
	ld hl, bdos
	; call bdos
	ld hl, 35
	ld hl, ft
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	pop de
	add hl, hl
	add hl, de
	push hl
	push hl
	; call bdos(2 args)
	call bdos
	ld hl, 4
	add hl, sp
	ld sp, hl
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	ld hl, ft
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 19
	pop de
	add hl, de
	pop de
	add hl, hl
	add hl, de
	push hl
	ld hl, ft
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 16
	pop de
	add hl, de
	pop de
	add hl, hl
	add hl, de
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	ld hl, ft
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 20
	pop de
	add hl, de
	pop de
	add hl, hl
	add hl, de
	push hl
	ld hl, ft
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 17
	pop de
	add hl, de
	pop de
	add hl, hl
	add hl, de
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	ld hl, ft
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 18
	pop de
	add hl, de
	pop de
	add hl, hl
	add hl, de
	push hl
	ld hl, 0
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	ld hl, ft
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 21
	pop de
	add hl, de
	pop de
	add hl, hl
	add hl, de
	push hl
	ld hl, 0
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	ld hl, 0
	; return
	ld sp, ix
	pop ix
	ret
.L21:
	ld hl, 1
	ex de, hl
	ld hl, 0
	or a
	sbc hl, de
	; return
	ld sp, ix
	pop ix
	ret
	; function fseek epilogue
	ld sp, ix
	pop ix
	ret
