; generated by hcbcomp-z80
; source: z80/fwrite.b


section text
extern ft
extern sb
global fwrite

section text
	; function fwrite prologue
fwrite:
	push ix
	ld ix, 0
	add ix, sp
	ld hl, -8
	add hl, sp
	ld sp, hl
	ld hl, 4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 0
	pop de
	or a
	sbc hl, de
	ld hl, 0
	jr nc, .L0
	inc hl
.L0:
	; || short-circuit
	ld a, h
	or l
	jp nz, .L1
	ld hl, 4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 5
	pop de
	or a
	sbc hl, de
	ld hl, 0
	jr c, .L3
	inc hl
.L3:
	ld a, h
	or l
	jp nz, .L1
	ld hl, 0
	jp .L2
.L1:
	ld hl, 1
.L2:
	; if
	ld a, h
	or l
	jp z, .L4
	ld hl, 1
	ex de, hl
	ld hl, 0
	or a
	sbc hl, de
	; return
	ld sp, ix
	pop ix
	ret
.L4:
	ld hl, -2
	add hl, ix
	push hl
	ld hl, 4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 24
	pop de
	push de
	push hl
	pop bc
	ld hl, 0
	ld a, 16
.L6:
	srl b
	rr c
	jr nc, .L7
	add hl, de
.L7:
	sla e
	rl d
	dec a
	jr nz, .L6
	pop de
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	ld hl, ft
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 23
	pop de
	add hl, de
	pop de
	add hl, hl
	add hl, de
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 0
	pop de
	or a
	sbc hl, de
	ld hl, 0
	jr nz, .L8
	inc hl
.L8:
	; if
	ld a, h
	or l
	jp z, .L9
	ld hl, 1
	ex de, hl
	ld hl, 0
	or a
	sbc hl, de
	; return
	ld sp, ix
	pop ix
	ret
.L9:
	ld hl, -4
	add hl, ix
	push hl
	ld hl, 0
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
.L11:
	ld hl, -4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	pop de
	or a
	sbc hl, de
	ld hl, 0
	jr nc, .L14
	inc hl
.L14:
	; while
	ld a, h
	or l
	jp z, .L13
	ld hl, -6
	add hl, ix
	push hl
	ld hl, ft
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 18
	pop de
	add hl, de
	pop de
	add hl, hl
	add hl, de
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	ld hl, -6
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 128
	pop de
	or a
	sbc hl, de
	ld hl, 0
	jr c, .L15
	inc hl
.L15:
	; if
	ld a, h
	or l
	jp z, .L16
	ld hl, ft
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 19
	pop de
	add hl, de
	pop de
	add hl, hl
	add hl, de
	push hl
	ld hl, ft
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 19
	pop de
	add hl, de
	pop de
	add hl, hl
	add hl, de
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 1
	pop de
	add hl, de
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	ld hl, ft
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 19
	pop de
	add hl, de
	pop de
	add hl, hl
	add hl, de
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 0
	pop de
	or a
	sbc hl, de
	ld hl, 0
	jr nz, .L18
	inc hl
.L18:
	; if
	ld a, h
	or l
	jp z, .L19
	ld hl, ft
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 20
	pop de
	add hl, de
	pop de
	add hl, hl
	add hl, de
	push hl
	ld hl, ft
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 20
	pop de
	add hl, de
	pop de
	add hl, hl
	add hl, de
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 1
	pop de
	add hl, de
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
.L19:
	ld hl, ft
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 18
	pop de
	add hl, de
	pop de
	add hl, hl
	add hl, de
	push hl
	ld hl, 0
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	ld hl, -6
	add hl, ix
	push hl
	ld hl, 0
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
.L16:
	ld hl, -6
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 0
	pop de
	or a
	sbc hl, de
	ld hl, 0
	jr nz, .L21
	inc hl
.L21:
	; if
	ld a, h
	or l
	jp z, .L22
	ld hl, ft
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 16
	pop de
	add hl, de
	pop de
	add hl, hl
	add hl, de
	push hl
	ld hl, ft
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 20
	pop de
	add hl, de
	pop de
	add hl, hl
	add hl, de
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 8
	pop de
	ex de, hl
	ld a, e
	or a
	jr z, .L24
.L25:
	add hl, hl
	dec a
	jr nz, .L25
.L24:
	push hl
	ld hl, ft
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 19
	pop de
	add hl, de
	pop de
	add hl, hl
	add hl, de
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	pop de
	ld a, e
	or l
	ld l, a
	ld a, d
	or h
	ld h, a
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	ld hl, ft
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 17
	pop de
	add hl, de
	pop de
	add hl, hl
	add hl, de
	push hl
	ld hl, 0
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
.L22:
	ld hl, sb
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, ft
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 18
	pop de
	add hl, de
	pop de
	add hl, hl
	add hl, de
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 2
	pop de
	ex de, hl
	ld a, 16
	ld bc, 0
.L26:
	push af
	add hl, hl
	rl c
	rl b
	ld a, c
	sub e
	ld c, a
	ld a, b
	sbc a, d
	ld b, a
	jr c, .L27
	inc hl
	jr .L28
.L27:
	ld a, c
	add a, e
	ld c, a
	ld a, b
	adc a, d
	ld b, a
.L28:
	pop af
	dec a
	jr nz, .L26
	pop de
	add hl, hl
	add hl, de
	push hl
	ld hl, 4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, -4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	pop de
	add hl, hl
	add hl, de
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	ld hl, ft
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 18
	pop de
	add hl, de
	pop de
	add hl, hl
	add hl, de
	push hl
	ld hl, ft
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 18
	pop de
	add hl, de
	pop de
	add hl, hl
	add hl, de
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 2
	pop de
	add hl, de
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	ld hl, -4
	add hl, ix
	push hl
	ld hl, -4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 1
	pop de
	add hl, de
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	ld hl, ft
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 18
	pop de
	add hl, de
	pop de
	add hl, hl
	add hl, de
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 128
	pop de
	or a
	sbc hl, de
	ld hl, 0
	jr c, .L29
	inc hl
.L29:
	; || short-circuit
	ld a, h
	or l
	jp nz, .L30
	ld hl, -4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	pop de
	or a
	sbc hl, de
	ld hl, 0
	jr nz, .L32
	inc hl
.L32:
	ld a, h
	or l
	jp nz, .L30
	ld hl, 0
	jp .L31
.L30:
	ld hl, 1
.L31:
	; if
	ld a, h
	or l
	jp z, .L33
extern set_dma
	ld hl, set_dma
	; call set_dma
	ld hl, sb
	push hl
	; call set_dma(1 args)
	call set_dma
	ld hl, 2
	add hl, sp
	ld sp, hl
	ld hl, -8
	add hl, ix
	push hl
extern bdos
	ld hl, bdos
	; call bdos
	ld hl, 34
	ld hl, ft
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	pop de
	add hl, hl
	add hl, de
	push hl
	push hl
	; call bdos(2 args)
	call bdos
	ld hl, 4
	add hl, sp
	ld sp, hl
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
.L33:
	jp .L11
.L13:
	ld hl, -4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	; return
	ld sp, ix
	pop ix
	ret
	; function fwrite epilogue
	ld sp, ix
	pop ix
	ret
