; generated by hcbcomp-z80
; source: gets.b


section text
extern getchar
global gets

section text
	; function gets prologue
gets:
	push ix
	ld ix, 0
	add ix, sp
	ld hl, -4
	add hl, sp
	ld sp, hl
	ld hl, -2
	add hl, ix
	push hl
	ld hl, 0
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
.L0:
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 254
	pop de
	or a
	sbc hl, de
	ld hl, 0
	jr nc, .L3
	inc hl
.L3:
	; while
	ld a, h
	or l
	jp z, .L2
	ld hl, -4
	add hl, ix
	push hl
	ld hl, getchar
	; call getchar
	; call getchar(0 args)
	call getchar
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	ld hl, -4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 10
	pop de
	or a
	sbc hl, de
	ld hl, 0
	jr nz, .L4
	inc hl
.L4:
	; if
	ld a, h
	or l
	jp z, .L5
	jp .L2
.L5:
	ld hl, -4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 13
	pop de
	or a
	sbc hl, de
	ld hl, 0
	jr nz, .L7
	inc hl
.L7:
	; if
	ld a, h
	or l
	jp z, .L8
	jp .L2
.L8:
	ld hl, -4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 1
	ex de, hl
	ld hl, 0
	or a
	sbc hl, de
	pop de
	or a
	sbc hl, de
	ld hl, 0
	jr nz, .L10
	inc hl
.L10:
	; if
	ld a, h
	or l
	jp z, .L11
	jp .L2
.L11:
	ld hl, 4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	pop de
	add hl, hl
	add hl, de
	push hl
	ld hl, -4
	add hl, ix
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	ld hl, -2
	add hl, ix
	push hl
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 1
	pop de
	add hl, de
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	jp .L0
.L2:
	ld hl, 4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	pop de
	add hl, hl
	add hl, de
	push hl
	ld hl, 0
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	; return
	ld sp, ix
	pop ix
	ret
	; function gets epilogue
	ld sp, ix
	pop ix
	ret
