; generated by hcbcomp-z80
; source: printf.b


section text
extern putchar
global _print_digit

section text
	; function _print_digit prologue
_print_digit:
	push ix
	ld ix, 0
	add ix, sp
	ld hl, 4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 10
	pop de
	or a
	sbc hl, de
	ld hl, 0
	jr c, .L0
	inc hl
.L0:
	; if
	ld a, h
	or l
	jp z, .L1
	ld hl, putchar
	; call putchar
	ld hl, 4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 10
	pop de
	ex de, hl
	or a
	sbc hl, de
	push hl
	ld hl, 97
	pop de
	add hl, de
	push hl
	; call putchar(1 args)
	call putchar
	ld hl, 2
	add hl, sp
	ld sp, hl
	jp .L2
.L1:
	ld hl, putchar
	; call putchar
	ld hl, 4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 48
	pop de
	add hl, de
	push hl
	; call putchar(1 args)
	call putchar
	ld hl, 2
	add hl, sp
	ld sp, hl
.L2:
	; function _print_digit epilogue
	ld sp, ix
	pop ix
	ret
global _print_u

section text
	; function _print_u prologue
_print_u:
	push ix
	ld ix, 0
	add ix, sp
	ld hl, -4
	add hl, sp
	ld sp, hl
	ld hl, -4
	add hl, ix
	push hl
	ld hl, 0
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	ld hl, 4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 0
	pop de
	or a
	sbc hl, de
	ld hl, 0
	jr nz, .L3
	inc hl
.L3:
	; if
	ld a, h
	or l
	jp z, .L4
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 0
	pop de
	add hl, hl
	add hl, de
	push hl
	ld hl, 48
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	ld hl, -4
	add hl, ix
	push hl
	ld hl, 1
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	jp .L5
.L4:
.L6:
	ld hl, 4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 0
	pop de
	or a
	sbc hl, de
	ld hl, 0
	jr z, .L9
	jr c, .L9
	inc hl
.L9:
	; while
	ld a, h
	or l
	jp z, .L8
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, -4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	pop de
	add hl, hl
	add hl, de
	push hl
	ld hl, 48
	push hl
	ld hl, 4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 10
	pop de
	ex de, hl
	ld a, 16
	ld bc, 0
.L10:
	push af
	add hl, hl
	rl c
	rl b
	ld a, c
	sub e
	ld c, a
	ld a, b
	sbc a, d
	ld b, a
	jr c, .L11
	inc hl
	jr .L12
.L11:
	ld a, c
	add a, e
	ld c, a
	ld a, b
	adc a, d
	ld b, a
.L12:
	pop af
	dec a
	jr nz, .L10
	push bc
	pop hl
	pop de
	add hl, de
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	ld hl, 4
	add hl, ix
	push hl
	ld hl, 4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 10
	pop de
	ex de, hl
	ld a, 16
	ld bc, 0
.L13:
	push af
	add hl, hl
	rl c
	rl b
	ld a, c
	sub e
	ld c, a
	ld a, b
	sbc a, d
	ld b, a
	jr c, .L14
	inc hl
	jr .L15
.L14:
	ld a, c
	add a, e
	ld c, a
	ld a, b
	adc a, d
	ld b, a
.L15:
	pop af
	dec a
	jr nz, .L13
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	ld hl, -4
	add hl, ix
	push hl
	ld hl, -4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 1
	pop de
	add hl, de
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	jp .L6
.L8:
.L5:
.L16:
	ld hl, -4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 0
	pop de
	or a
	sbc hl, de
	ld hl, 0
	jr z, .L19
	jr c, .L19
	inc hl
.L19:
	; while
	ld a, h
	or l
	jp z, .L18
	ld hl, -4
	add hl, ix
	push hl
	ld hl, -4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 1
	pop de
	ex de, hl
	or a
	sbc hl, de
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	ld hl, putchar
	; call putchar
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, -4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	pop de
	add hl, hl
	add hl, de
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	; call putchar(1 args)
	call putchar
	ld hl, 2
	add hl, sp
	ld sp, hl
	jp .L16
.L18:
	; function _print_u epilogue
	ld sp, ix
	pop ix
	ret
global _print_s

section text
	; function _print_s prologue
_print_s:
	push ix
	ld ix, 0
	add ix, sp
	ld hl, -2
	add hl, sp
	ld sp, hl
	ld hl, -2
	add hl, ix
	push hl
	ld hl, 0
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
.L20:
	ld hl, 4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	pop de
	add hl, hl
	add hl, de
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 0
	pop de
	or a
	sbc hl, de
	ld hl, 0
	jr z, .L23
	inc hl
.L23:
	; while
	ld a, h
	or l
	jp z, .L22
	ld hl, putchar
	; call putchar
	ld hl, 4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	pop de
	add hl, hl
	add hl, de
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	; call putchar(1 args)
	call putchar
	ld hl, 2
	add hl, sp
	ld sp, hl
	ld hl, -2
	add hl, ix
	push hl
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 1
	pop de
	add hl, de
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	jp .L20
.L22:
	; function _print_s epilogue
	ld sp, ix
	pop ix
	ret
global _print_x

section text
	; function _print_x prologue
_print_x:
	push ix
	ld ix, 0
	add ix, sp
	ld hl, -6
	add hl, sp
	ld sp, hl
	ld hl, -2
	add hl, ix
	push hl
	ld hl, 0
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
.L24:
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 4
	pop de
	or a
	sbc hl, de
	ld hl, 0
	jr nc, .L27
	inc hl
.L27:
	; while
	ld a, h
	or l
	jp z, .L26
	ld hl, -4
	add hl, ix
	push hl
	ld hl, 12
	push hl
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 4
	pop de
	push de
	push hl
	pop bc
	ld hl, 0
	ld a, 16
.L28:
	srl b
	rr c
	jr nc, .L29
	add hl, de
.L29:
	sla e
	rl d
	dec a
	jr nz, .L28
	pop de
	pop de
	ex de, hl
	or a
	sbc hl, de
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	ld hl, -6
	add hl, ix
	push hl
	ld hl, 4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, -4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	pop de
	ex de, hl
	ld a, e
	or a
	jr z, .L30
.L31:
	srl h
	rr l
	dec a
	jr nz, .L31
.L30:
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	ld hl, -6
	add hl, ix
	push hl
	ld hl, -6
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 15
	pop de
	ld a, e
	and l
	ld l, a
	ld a, d
	and h
	ld h, a
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
extern _print_digit
	ld hl, _print_digit
	; call _print_digit
	ld hl, -6
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	; call _print_digit(1 args)
	call _print_digit
	ld hl, 2
	add hl, sp
	ld sp, hl
	ld hl, -2
	add hl, ix
	push hl
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 1
	pop de
	add hl, de
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	jp .L24
.L26:
	; function _print_x epilogue
	ld sp, ix
	pop ix
	ret
global printf

section text
	; function printf prologue
printf:
	push ix
	ld ix, 0
	add ix, sp
	ld hl, -6
	add hl, sp
	ld sp, hl
	ld hl, -2
	add hl, ix
	push hl
	ld hl, 0
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	ld hl, -6
	add hl, ix
	push hl
	ld hl, 4
	add hl, ix
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
.L32:
	ld hl, 1
	; while
	ld a, h
	or l
	jp z, .L34
	ld hl, -4
	add hl, ix
	push hl
	ld hl, 4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	pop de
	add hl, hl
	add hl, de
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	ld hl, -4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 0
	pop de
	or a
	sbc hl, de
	ld hl, 0
	jr nz, .L35
	inc hl
.L35:
	; if
	ld a, h
	or l
	jp z, .L36
	; return
	ld sp, ix
	pop ix
	ret
.L36:
	ld hl, -4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 37
	pop de
	or a
	sbc hl, de
	ld hl, 0
	jr nz, .L38
	inc hl
.L38:
	; if
	ld a, h
	or l
	jp z, .L39
	ld hl, -2
	add hl, ix
	push hl
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 1
	pop de
	add hl, de
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	ld hl, -4
	add hl, ix
	push hl
	ld hl, 4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	pop de
	add hl, hl
	add hl, de
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	ld hl, -4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 100
	pop de
	or a
	sbc hl, de
	ld hl, 0
	jr nz, .L41
	inc hl
.L41:
	; if
	ld a, h
	or l
	jp z, .L42
	ld hl, -6
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 32768
	pop de
	ld a, e
	and l
	ld l, a
	ld a, d
	and h
	ld h, a
	; if
	ld a, h
	or l
	jp z, .L44
	ld hl, putchar
	; call putchar
	ld hl, 45
	push hl
	; call putchar(1 args)
	call putchar
	ld hl, 2
	add hl, sp
	ld sp, hl
extern _print_u
	ld hl, _print_u
	; call _print_u
	ld hl, 0
	push hl
	ld hl, -6
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	pop de
	ex de, hl
	or a
	sbc hl, de
	push hl
	; call _print_u(1 args)
	call _print_u
	ld hl, 2
	add hl, sp
	ld sp, hl
	jp .L45
.L44:
	ld hl, _print_u
	; call _print_u
	ld hl, -6
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	; call _print_u(1 args)
	call _print_u
	ld hl, 2
	add hl, sp
	ld sp, hl
.L45:
	ld hl, -6
	add hl, ix
	push hl
	ld hl, -6
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 1
	pop de
	add hl, de
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	jp .L43
.L42:
	ld hl, -4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 117
	pop de
	or a
	sbc hl, de
	ld hl, 0
	jr nz, .L46
	inc hl
.L46:
	; if
	ld a, h
	or l
	jp z, .L47
	ld hl, _print_u
	; call _print_u
	ld hl, -6
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	; call _print_u(1 args)
	call _print_u
	ld hl, 2
	add hl, sp
	ld sp, hl
	ld hl, -6
	add hl, ix
	push hl
	ld hl, -6
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 1
	pop de
	add hl, de
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	jp .L48
.L47:
	ld hl, -4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 120
	pop de
	or a
	sbc hl, de
	ld hl, 0
	jr nz, .L49
	inc hl
.L49:
	; if
	ld a, h
	or l
	jp z, .L50
extern _print_x
	ld hl, _print_x
	; call _print_x
	ld hl, -6
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	; call _print_x(1 args)
	call _print_x
	ld hl, 2
	add hl, sp
	ld sp, hl
	ld hl, -6
	add hl, ix
	push hl
	ld hl, -6
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 1
	pop de
	add hl, de
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	jp .L51
.L50:
	ld hl, -4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 115
	pop de
	or a
	sbc hl, de
	ld hl, 0
	jr nz, .L52
	inc hl
.L52:
	; if
	ld a, h
	or l
	jp z, .L53
extern _print_s
	ld hl, _print_s
	; call _print_s
	ld hl, -6
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	; call _print_s(1 args)
	call _print_s
	ld hl, 2
	add hl, sp
	ld sp, hl
	ld hl, -6
	add hl, ix
	push hl
	ld hl, -6
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 1
	pop de
	add hl, de
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	jp .L54
.L53:
	ld hl, -4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 99
	pop de
	or a
	sbc hl, de
	ld hl, 0
	jr nz, .L55
	inc hl
.L55:
	; if
	ld a, h
	or l
	jp z, .L56
	ld hl, putchar
	; call putchar
	ld hl, -6
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	; call putchar(1 args)
	call putchar
	ld hl, 2
	add hl, sp
	ld sp, hl
	ld hl, -6
	add hl, ix
	push hl
	ld hl, -6
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 1
	pop de
	add hl, de
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	jp .L57
.L56:
	ld hl, -4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 37
	pop de
	or a
	sbc hl, de
	ld hl, 0
	jr nz, .L58
	inc hl
.L58:
	; if
	ld a, h
	or l
	jp z, .L59
	ld hl, putchar
	; call putchar
	ld hl, 37
	push hl
	; call putchar(1 args)
	call putchar
	ld hl, 2
	add hl, sp
	ld sp, hl
.L59:
.L57:
.L54:
.L51:
.L48:
.L43:
	ld hl, -2
	add hl, ix
	push hl
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 1
	pop de
	add hl, de
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	jp .L40
.L39:
	ld hl, putchar
	; call putchar
	ld hl, -4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	; call putchar(1 args)
	call putchar
	ld hl, 2
	add hl, sp
	ld sp, hl
	ld hl, -2
	add hl, ix
	push hl
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 1
	pop de
	add hl, de
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
.L40:
	jp .L32
.L34:
	; function printf epilogue
	ld sp, ix
	pop ix
	ret
