; generated by hcbcomp-z80
; source: strcat.b


section text
global strcat

section text
	; function strcat prologue
strcat:
	push ix
	ld ix, 0
	add ix, sp
	ld hl, -4
	add hl, sp
	ld sp, hl
	ld hl, -2
	add hl, ix
	push hl
	ld hl, 0
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
.L0:
	ld hl, 4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	pop de
	add hl, hl
	add hl, de
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 0
	pop de
	or a
	sbc hl, de
	ld hl, 0
	jr z, .L3
	inc hl
.L3:
	; while
	ld a, h
	or l
	jp z, .L2
	ld hl, -2
	add hl, ix
	push hl
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 1
	pop de
	add hl, de
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	jp .L0
.L2:
	ld hl, -4
	add hl, ix
	push hl
	ld hl, 0
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
.L4:
	ld hl, 4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, -4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	pop de
	add hl, hl
	add hl, de
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 0
	pop de
	or a
	sbc hl, de
	ld hl, 0
	jr z, .L7
	inc hl
.L7:
	; while
	ld a, h
	or l
	jp z, .L6
	ld hl, 4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	pop de
	add hl, hl
	add hl, de
	push hl
	ld hl, 4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, -4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	pop de
	add hl, hl
	add hl, de
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	ld hl, -2
	add hl, ix
	push hl
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 1
	pop de
	add hl, de
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	ld hl, -4
	add hl, ix
	push hl
	ld hl, -4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, 1
	pop de
	add hl, de
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	jp .L4
.L6:
	ld hl, 4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	push hl
	ld hl, -2
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	pop de
	add hl, hl
	add hl, de
	push hl
	ld hl, 0
	pop de
	ex de, hl
	ld [hl], e
	inc hl
	ld [hl], d
	ld hl, 4
	add hl, ix
	ld a, [hl]
	inc hl
	ld h, [hl]
	ld l, a
	; return
	ld sp, ix
	pop ix
	ret
	; function strcat epilogue
	ld sp, ix
	pop ix
	ret
